### ISSUE TITLE
Starter project: arrow keys to pan map

### ISSUE THREAD

**Issue by dabreegster** [dabreegster/abstreet#10]
Panning the map today uses the mouse to click and drag. Players also expect to use arrow keys. This is pretty simple to add to https://github.com/dabreegster/abstreet/blob/573edbd13e5aa4bedba0bd819d3d7b32dba11b59/ezgui/src/canvas.rs#L93, but the complication is that arrow keys are currently used in some GUI menus. I think there are cases where the menus are active, but the player can still drag around the map underneath. We should probably redesign that a bit first, or maybe just disable canvas map scrolling by arrow key in that case.

**Comment by rileythomp** [comment]
I could try this if still needed

**Comment by dabreegster** [comment]
Sure, this would still be useful! I think when popup menus using arrow keys are open now, the map underneath can't be interacted with at all, so there shouldn't usually be a conflict over the keys. Should be pretty straightforward -- let me know if not.
