### ISSUE TITLE
When selecting a region, region fills and click targets are out of place

### ISSUE THREAD

**Issue by jraymakers** [dabreegster/abstreet#101]
Screenshot below. Notice how the red "Downtown Seattle" region appears over the mouth of the ship canal. That's the click target as well; clicking on downtown doesn't go there. Other regions are similarly out of place, with a similar scaling factor.

I'm running on a Mac, OS 10.14.6, with a 15 inch Retina display (2880 x 1800).

This was built from source just a few minutes ago (around 8pm Pacific on 2020-06-24).

<img width="1440" alt="Screen Shot 2020-06-24 at 7 54 40 PM" src="https://user-images.githubusercontent.com/3701900/85648910-a6cb3780-b656-11ea-8c33-6e68e7e6602c.png">

**Comment by dabreegster** [comment]
I can repro by forcing `--scale_factor=1.5`. The math in `city_picker.rs` probably needs to account for this, I'll fix it tonight
