### ISSUE TITLE
Buttons not clickable

### ISSUE THREAD

**Issue by rishit-khandelwal** [dabreegster/abstreet#105]
I am not able to get past play button unless i press enter and even after that I can't press any button to start playing the game. :(

**Comment by rishit-khandelwal** [comment]
Here is the video:
https://drive.google.com/file/d/1PXinyNRdnEn_5FuOR3iB5tpEz87VKwhe/view?usp=sharing

**Comment by dabreegster** [comment]
Really strange. Even if the button hitboxes are offset from the window because of some monitor scaling factor problem, on the second screen, you should've hit something moving around. If you resize the window, does it help anything? If not, I can add some debug statements to print where the mouse is, where buttons get placed, etc

**Comment by rishit-khandelwal** [comment]
Yeah try that too.

**Comment by dabreegster** [comment]
Rishit, could you please also try this:

Get past the screensaver by pressing **enter**, then get into sandbox mode by pressing **s**. Then once you're at the map, try clicking and dragging it. Does anything in the map respond to your mouse at all, or is it just all of the menus and buttons?

**Comment by dabreegster** [comment]
Someone by email hit the same problem and said this worked for them:

-opening the program
-then right clicking the program in the task bar at the bottom of the screen
-clicking game.exe
-Clicking Run

I have no earthly idea what's going on if this is indeed a workaround.

**Comment by rishit-khandelwal** [comment]
Pressing 's' works. It works on the sandbox. Seems to be a problem with the
menu.

**Comment by rishit-khandelwal** [comment]
> Someone by email hit the same problem and said this worked for them:
> 
> -opening the program
> -then right clicking the program in the task bar at the bottom of the screen
> -clicking game.exe
> -Clicking Run
> 
> I have no earthly idea what's going on if this is indeed a workaround.

Yeah, this works /|\
                            |

**Comment by rishit-khandelwal** [comment]
Is this fixed? Because I switched the PC so I can't test on that PC.

**Comment by dabreegster** [comment]
I haven't changed anything to fix this problem, but also I've never been able to reproduce it. Since there's nothing actionable to do, I'll close the bug. If somebody new comes along and can reproduce it and help debug, we can reopen. Thanks!
