### ISSUE TITLE
Can't compile due to 'non-exhaustive patterns: `LightRail` not covered'

### ISSUE THREAD

**Issue by wallentx** [dabreegster/abstreet#108]
https://github.com/dabreegster/abstreet/blob/v0.2.1/map_model/src/lane.rs#L35

> error[E0004]: non-exhaustive patterns: `LightRail` not covered
>    --> map_editor/src/model.rs:579:27
>     |
> 579 |         let color = match lt {
>     |                           ^^ pattern `LightRail` not covered
>     | 
>    ::: /home/william/source/abstreet/map_model/src/lane.rs:35:5
>     |
> 35  |     LightRail,
>     |     --------- not covered
>     |
>     = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
>     = note: the matched value is of type `map_model::lane::LaneType`
>

**Comment by dabreegster** [comment]
Sorry about that, fixed now. The `map_editor` crate is unused right now, but you'd hit this if you're `cargo build`ing from the root dir
