### ISSUE TITLE
Removing the VIP's parking crashes the game

### ISSUE THREAD

**Issue by belt-drive** [dabreegster/abstreet#109]
Playing the "VIP commute" challenge. VIP starts the challenge with the car parked on the north side of the street. If this parking lane is removed (i.e. by converting to a bike lane), the game crashes when attempting to return from the editing session.

Not sure if it matters, but using the Mac version of the game.

For the record, I was trying to get this dumbo to park on the same side of the street as their residence by forcibly removing their parking. They walk incredibly slowly and are unwilling to jaywalk :(

**Comment by belt-drive** [comment]
To clarify: if the parking is removed *before the VIP begins their first trip of the day*

**Comment by dabreegster** [comment]
Thanks for reporting! Could you send the output.txt file? I can't reproduce the crash.

The pedestrian movement model is simplified right now; no jay-walking even across quiet neighborhood streets. Amusingly enough, people also can't walk at all along roads that don't have any sidewalks. There are plenty of alleyways and residential roads in north seattle without sidewalks, so this is a bit of a problem. I have some ideas for ways to model over-taking that could help with cars/pedestrians sharing the same "lane".

**Comment by belt-drive** [comment]
Output file should be attached here. One other detail that seems to be important for the repro: switch the direction of travel on the road in front of the VIPs's house, as well as the direction of the parking lane.
[output.txt](https://github.com/dabreegster/abstreet/files/4854677/output.txt)

**Comment by dabreegster** [comment]
Thanks! This is related to #64. The bug is [here](https://github.com/dabreegster/abstreet/blob/9b42d27e8529dd0e25f17802c23f5f9c5a732144/map_model/src/road.rs#L162), it only looks for driving lanes to the left of the parking lane. I'll make it handle both sides
