### ISSUE TITLE
Add prerequisites to new_city.md

### ISSUE THREAD

**Issue by jvolker** [dabreegster/abstreet#117]
The new city import guide is missing prerequisites.

Maybe link to https://github.com/dabreegster/abstreet/blob/master/docs/dev.md#getting-started or just https://www.rust-lang.org/tools/install. I'm not sure what's necessary.

Thanks for this amazing project!

**Comment by dabreegster** [comment]
The instructions are confusing because there are a few combinations of things people might be trying to do: running the importer in the binary release, compiling just the game from source, building map data from source, etc. How's the wording now? Any ideas for arranging it more clearly?

**Comment by jvolker** [comment]
Maybe it's best to break it up into multiple paragraphs.

I'm just doing my first steps here. First I was using https://github.com/dabreegster/abstreet/releases/download/v0.2.1/abstreet_mac_v0_2_1.zip from the readme. I guess that's what's called the binary release. But then following `new_city.md` …

> If you're using a binary release, you have to be sure to run the tool from the importer/ directory, so that ../data/ exists: cd importer; ./importer --oneshot=/absolute/path/to/file.osm

… I'm getting this error:

`./importer: No such file or directory`

That's why I'm now trying the dev version / from source.

**Comment by jvolker** [comment]
As mentioned in https://github.com/dabreegster/abstreet/issues/118#issuecomment-653024952 this paragraph is important https://github.com/dabreegster/abstreet/blob/master/docs/dev.md#building-map-data and should probably be mentioned here.

**Comment by dabreegster** [comment]
> ./importer: No such file or directory

I just checked the release, I think this file should be in the unzipped archive. Is it missing for you?

```
[9][~/Downloads/abstreet_mac_v0_2_1]$ ls
data  game  importer  INSTRUCTIONS.md  play_abstreet.sh

[9][~/Downloads/abstreet_mac_v0_2_1]$ ls importer/
importer
```

I'll work on re-wording the new_city doc

**Comment by jvolker** [comment]
Sorry … my bad. I just checked again and I was mixing up my binary and source versions. Sorry about that.

The import is currently running in the binary version. I'll post again if I run into more trouble.

**Comment by matkoniecz** [comment]
For me import instruction seemed clear (though I have not succeeded for now).

Though for me as an OSM expert it was clear how can I obtain .osm files, it may be a barrier for others.

https://github.com/dabreegster/abstreet/blob/master/docs/new_city.md - maybe put binary release paragraph first? Seems easiest and the most accessible.
