### ISSUE TITLE
Crash when switching to all Seattle map in sandbox

### ISSUE THREAD

**Issue by belt-drive** [dabreegster/abstreet#121]
If I open the sandbox mode and try to select the all Seattle map, the game crashes. I can select other maps without a crash. Output file included below.
[output.txt](https://github.com/dabreegster/abstreet/files/4866973/output.txt)

**Comment by dabreegster** [comment]
Fixed by https://github.com/dabreegster/abstreet/commit/1617a3d3c110d455bcf123aa945daaaea0b9b384, it'll be in the next build
