### ISSUE TITLE
Adaptive signals fail during gridlock

### ISSUE THREAD

**Issue by belt-drive** [dabreegster/abstreet#124]
If there is a consistent backup with no throughput at an intersection with an adaptive signal, that signal will never switch, which can compound gridlock. Recommend adding a clause to the adaptive signal timing algorithm to include intersection throughput as a consideration, if possible. If there is high demand in one direction but 1 (or more) cycles of the signal that would facilitate movement in that direction has no throughput, do not keep repeating that phase of the light cycle.

**Comment by dabreegster** [comment]
The rules for the adaptive signal (a misnomer, it's more like actuated) are almost deliberately simple right now. When a phase is about to end, if there's anyone waiting at the end of the queue to start a protected turn in that phase, repeat the entire phase. I can imagine a huge set of possible parameters to picking the next phase and maybe modifying its duration. Looking at demand in different directions is a good start. One thing that'd be helpful to me is if anybody familiar with actuated signals in practice or who's thought about these policies to describe as precisely as possible how they should work, what parameters should be tuneable in the UI, etc. I can implement it. I haven't spent much time yet researching how signals work in practice or trying out different policies; I see myself more as a builder of tools for people with ideas for policies. :)
