### ISSUE TITLE
Starter project: title screen should have some traffic

### ISSUE THREAD

**Issue by dabreegster** [dabreegster/abstreet#13]
The title screen shows a "screensaver" that bounces randomly around an empty map. It'd be more interesting to have some traffic running, and maybe to follow some agents for a while. https://github.com/dabreegster/abstreet/blob/9ba4f83ca47e0d5902115ac2e471709a7313864f/game/src/pregame.rs#L137

**Comment by dabreegster** [comment]
(Ignore this, just testing a Figma embedding plugin)

https://www.figma.com/file/RX2nOdY2uPaqGGvWPyDvV6/A%2FB-Street?node-id=1178%3A991

**Comment by RestitutorOrbis** [comment]
Is `abstreet/game/src/pregame.rs` the only relevant file for this issue?

**Comment by dabreegster** [comment]
Changes should go here and apply to `TitleScreen`. To spawn random traffic, you could use `spawn_agents_around` or `ScenarioGenerator::small_run`. To follow an agent, you'd do `ctx.canvas.center_on_map_pt(app.primary.sim.canonical_pt_for_agent(...))`
