### ISSUE TITLE
Add "how can I add missing data to OSM" section?

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#133]
Would it be useful/welcome to have a section mentioning how can one add the missing data to OSM in the readme? I noticed the editor inside the program, but maybe something also in readme would be useful? Probably mentioning what kind of data is used, mentioning that iD editor is quite reasonable and linking JOSM may be useful.

Maybe also mentioning StreetComplete.

I would be willing to make a PR - I though about "you can also help by improving OpenStreetMap data" linking to a separate documentation file.

**Comment by matkoniecz** [comment]
I found https://github.com/dabreegster/abstreet/blob/master/docs/roadmap.md#contributing-for-non-programmers that is a bit hidden

**Comment by dabreegster** [comment]
A PR would be incredibly welcome, thank you! I'm trying (and failing) to keep the main README somewhat short, so a prominent link to a separate doc talking about iD, StreetComplete, etc would be preferable.
