### ISSUE TITLE
Broken markdown in docs/west_seattle/proposal.md

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#135]
https://github.com/dabreegster/abstreet/blob/master/docs/west_seattle/proposal.md claims to be a markdown file, but has a failing iframe code.

It may be deficiency of github markdown and unfixable.

**Comment by dabreegster** [comment]
It shows up here: https://dabreegster.github.io/abstreet/west_seattle/proposal.html

I searched around for a way to embed videos in Markdown, and the iframe approach is the only I found. I might try to reorganize most of the docs around the .io page eventually.
