### ISSUE TITLE
found a virtual manifest at `Cargo.toml` instead of a package manifest

### ISSUE THREAD

**Issue by yurivict** [dabreegster/abstreet#137]
```abstreet``` builds but the ```install``` target fails:
```
error: found a virtual manifest at `/usr/ports/misc/abstreet/work/abstreet-0.2.2-1-g3f912e22/Cargo.toml` instead of a package manifest
```

The failed command:
```
cd /usr/ports/misc/abstreet/work/abstreet-0.2.2-1-g3f912e22 && /usr/bin/env XDG_DATA_HOME=/usr/ports/misc/abstreet/work  XDG_CONFIG_HOME=/usr/ports/misc/abstreet/work  HOME=/usr/ports/misc/abstreet/work PATH=/usr/ports/misc/abstreet/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer -isystem /usr/local/include"  LDFLAGS=" -fstack-protector-strong -L/usr/local/lib " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" CARGO_HOME=/usr/ports/misc/abstreet/work/cargo-home  CARGO_BUILD_JOBS=8  CARGO_TARGET_DIR=/usr/ports/misc/abstreet/work/target  RUST_BACKTRACE=1  RUSTC=/usr/local/bin/rustc  RUSTDOC=/usr/local/bin/rustdoc  RUSTFLAGS=" -C linker=cc -C link-arg=-fstack-protector-strong -C link-arg=-L/usr/local/lib"  /usr/local/bin/cargo install  --no-track  --path "."  --root "/usr/ports/misc/abstreet/work/stage/usr/local"  --verbose  
```

FreeBSD 12.1
rust-1.44.1_1

**Comment by dabreegster** [comment]
Ah, it's split into crates. You probably want to `cd game; cargo build`.

**Comment by yurivict** [comment]
The framework doesn't seem to support this.

What files are required to be installed for ```abstreet``` to run?

It seems to reference files "../data/...". But if I would install the executable into /usr/local/bin/abstreet-game these files can't be make available because supporting files should go into /usr/local/share/abstreet.

It also expects the file ```montlake.bin```.

When I download this file it fails:
```
$ ./release/game 
Inner window size is PhysicalSize { width: 1920, height: 994 }, monitor is PhysicalSize { width: 1920, height: 1080 }, scale factor is 1
load map...
Loading map ../data/system/maps/montlake.bin
Reading ../data/system/maps/montlake.bin: 0/2 MB... 0.0000smemory allocation of 17394427201963978351 bytes failedAbort trap
```

**Comment by dabreegster** [comment]
You need to run the updater: https://github.com/dabreegster/abstreet/blob/master/docs/dev.md#getting-started

Putting the data files in a totally different directory makes sense for packaging in a distro. I have #73 filed to stop relying on relative paths. My solution for that was going to be to check the current directory for `data/`, and if it's not there, try `../data/`, since most of the problems people have had so far have been trying to run the binary from the project's root directory.

But for a totally different /usr/local/share case, how should the binary know to look here? Are there best practices for this sort of thing that're reasonably cross platform?

**Comment by yurivict** [comment]
> But for a totally different /usr/local/share case, how should the binary know to look here? Are there best practices for this sort of thing that're reasonably cross platform?

Build-time options.
For C++ cmake-built projects one might have a cmake option telling the build where to look for files.
I am not an expert in Rust, so I don't know what is the best way to achieve the same for a Rust project.

**Comment by dabreegster** [comment]
Ah, that makes sense. I think Rust can do this by passing env vars to a build script: https://doc.rust-lang.org/cargo/reference/build-scripts.html#inputs-to-the-build-script

I'll overhaul the relative path handling sometime this week and support this sort of thing. Should get to it in a few days

**Comment by dabreegster** [comment]
Also relevant if you're trying to package abstreet: check out the scripts in `release`

**Comment by yurivict** [comment]
> I think Rust can do this by passing env vars to a build script

Also environment is best checked at build-time (like cmake options are). In case it's run-time a shell wrapper would be required to provide the needed environment variables.

**Comment by dabreegster** [comment]
You can now stash `data/` anywhere. When you build, use `ABST_DATA_DIR=/some/path`. Let me know if there's anything else I can adjust to make it possible to build+package on FreeBSD!
