### ISSUE TITLE
building map data from source distribution failed (Result::unwrap()` on an `Err` value)

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#138]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', convert_osm/src/osm_reader.rs:31:26
```

gist: https://gist.github.com/matkoniecz/6e1120f518f3e421402f97ded046c295

I was running `./import.sh --oneshot=test.osm`

I followed https://github.com/dabreegster/abstreet/issues/118#issuecomment-653108408 to avoid dealing with gdal bindings (though gdal is installed).

`test.osm` file exists ` osmconvert` is available, `rustc` at correct version is available (though I installed via some suspicious rustup rather than from a proper package).

```
mateusz@grisznak:~/Downloads/abstreet$ osmconvert --help | grep 0.8.1
osmconvert 0.8.10
mateusz@grisznak:~/Downloads/abstreet$ rustc --version
rustc 1.44.1 (c7087fe00 2020-06-17)
mateusz@grisznak:~/Downloads/abstreet$ cat test.osm | tail -n 1
</osm>
mateusz@grisznak:~/Downloads/abstreet$ cat ./import.sh
#!/bin/bash

cd importer;
RUST_BACKTRACE=1 cargo run --release -- $@;
cd ..;
mateusz@grisznak:~/Downloads/abstreet$

**Comment by dabreegster** [comment]
I should be more clear in `docs/new_city.md`. The path has to be absolute, because `import.sh` sneakily `cd`s into the `importer` directory, so that the rest of the system finds `../data/` where it expects. #73 is the root problem here.

**Comment by matkoniecz** [comment]
OK, it run now. I will close it, hopefully people searching for it will see it (feel free to reopen if you want).

**Comment by matkoniecz** [comment]
And thanks for a help!

**Comment by dabreegster** [comment]
No problem! I'll probably fix the weird relative dir issue in the next few days, because somebody else is hitting problems with it too
