### ISSUE TITLE
thread 'main' panicked at 'Unknown turn restriction accessway', map_model/src/raw.rs:374:18

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#142]
It seems that it is case of invalid data, but maybe it would be better to skip processing this specific relation, loudly complain and continue?

I tried to load entire Kraków and AB crashed on this.

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/relation/5132017#map=18/50.07971/20.00431
https://www.openstreetmap.org/relation/5132016

No idea about meaning (I will ask the author), can be safely skipped.

**Comment by dabreegster** [comment]
Assuming you're building from source, the temporary workaround is to just update `raw.rs` in the line number referenced. There's a bunch of nuance with turn restrictions that's completely glossed over right now.

I'm considering failing open here, but so far it's been kind of nice to track what different values might be encountered in practice. I guess I could just use taginfo instead

**Comment by matkoniecz** [comment]
Taginfo/OSM Wiki would be better. There is long tail of mispelled tags, bizarre ideas, one-shot tagging experiments. See https://taginfo.openstreetmap.org/keys/restriction#values - 333 entries, just 9 used more than 1000 times worldwide.
