### ISSUE TITLE
Parking lots without parking_aisles have no spots

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#150]
https://www.openstreetmap.org/way/156554614

private parkings are also used by cars traveling on public roads so assigning 0 capacity is weird

Even if private parkings should be skipped then not displaying them at all would be better than 0/0 ghost ones

![screen](https://user-images.githubusercontent.com/899988/86785509-06681080-c063-11ea-9459-4b04858ac221.png)

**Comment by matkoniecz** [comment]
I admit that I have not tested public parkings, maybe parkings are broken in general?

**Comment by dabreegster** [comment]
Parking lots are a WIP. I'm relying on parking aisles like https://www.openstreetmap.org/way/688297818 right now. These aisles are clipped to the lot's polygon, then I have a really simple [algorithm](https://github.com/dabreegster/abstreet/blob/187c8ad4c56cc119c52493210af8e340a167402d/map_model/src/make/buildings.rs#L270) that tries to draw individual slots along the aisles. This way doesn't have any aisles, so right now it doesn't get assigned spots. From the area of this polygon alone, we should instead estimate how many car could be parked here, and come up with some reasonable way to render it. Ideas welcome.

**Comment by matkoniecz** [comment]
> Ideas welcome.

What form of ideas is useful? Is it useful to post ideas without code or is it something to be interpreted as "PR welcome"?

**Comment by dabreegster** [comment]
"PR welcome" is way too high a bar. :)  Ideas, pseudocode, diagrams, references to other projects solving something similar, etc. For example, "detect if the parking lot polygon is a rectangle. if so, find the two main axes, and lay out spots in a grid with X meter length."
