### ISSUE TITLE
no way to distinguish "give way" and "stop" junctions

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#151]
I see no way to distinguish "give way" and "stop" junctions.

Only open crossing types are "stop signs" and "traffic light"

Not sure whatever USA has no such distinction or is it just skipped for now.

**Comment by matkoniecz** [comment]
It turns to be not relevant as acceleration is not modelled.

**Comment by dabreegster** [comment]
You can edit a stop sign-controlled intersection and turn off all the signs. Then everybody yields, but doesn't pause for `WAIT_AT_STOP_SIGN = 0.5s`

**Comment by matkoniecz** [comment]
Hm, so vehicles encountering stop sign on an empty crossing are actually wasting time?

**Comment by dabreegster** [comment]
Yes, but only 0.5s? Stop signs are generated when the rank of roads at an intersection is all the same: https://github.com/dabreegster/abstreet/blob/476e0e101f738b74c30ae1b4a40673ed6fe006f4/map_model/src/objects/stop_signs.rs#L92
Rank determined from the `highway` tag: https://github.com/dabreegster/abstreet/blob/476e0e101f738b74c30ae1b4a40673ed6fe006f4/map_model/src/objects/road.rs#L353

If you have a better idea for guessing what direction will have a stop sign, it should be easy to implement. Coverage of `highway=stop` isn't good enough to rely on, and it's quite tedious to tag.
