### ISSUE TITLE
better default "random" traffic patterns

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#154]
see https://github.com/dabreegster/abstreet/issues/154#issuecomment-658026415 for current plans

see https://github.com/dabreegster/abstreet/issues/205#issuecomment-660707593 for warp hint

--------------------

`sim/src/make/generator.rs` contains code for generating trips

See https://github.com/dabreegster/abstreet/pull/183/files for related code 

See https://github.com/dabreegster/abstreet/commit/ead4a99682d11ec4af4824a1ab4c3854bae7b0d4 for related code

-----------------------------------------------------------------------------------------

I have no idea how "random" traffic generation works, but currently it results in poor results for large maps.

Initial traffic at midnight seemed reasonable (maybe bicycle traffic was too high and bus traffic was too low), but later instead of ramping up it started dropping!

I expected game melting down/crashing on attempting to simulate tens (hundreds?) thousands of active trips at once rather than drop to zero active trips.

EDIT: yes, it is a prime example of not reading warnings. Random is described to behave in this way - see https://github.com/dabreegster/abstreet/commit/da1731ccb2d549ed95516de76881ab53f67e8dd3#diff-628ee6879bfcdd889804ae5371c9a26cR223

**Comment by dabreegster** [comment]
For maps without separate trip input demand (aka, all of them except seattle), currently just making up a really basic input: https://github.com/dabreegster/abstreet/blob/187c8ad4c56cc119c52493210af8e340a167402d/sim/src/make/generator.rs#L96

Coming up with more realistic patterns in general is hard, but I think this default option could be improved in easy ways. Maybe have a UI ask how many new trips per hour, then spawn a constant load throughout the day, or distribute more of the weight around morning/afternoon rush hour. Even cooler would be to classify buildings as (purely) residential or commercial based on OSM tags (check out layers > amenities) and come up with some patterns like "a person goes from a residence to a random business sometime between 6-9am, then a random restaurant at 6-8pm, then back home."

If you have any ideas for this sort of heuristic schedule, I'd be glad to implement it. As I work with planners from more cities, I'm getting a better idea of how this trip demand data gets created. Hopefully there are some better defaults we can do. One of the problems is getting a rough population count for a given area.

**Comment by matkoniecz** [comment]
> One of the problems is getting a rough population count for a given area.

It sounds like something estimable from building tags such as `buidling` `building:use` (for its type - see large `building=warehouse` vs large `building=apartments`), building size and `building:levels`.

**Comment by matkoniecz** [comment]
> If you have any ideas for this sort of heuristic schedule, I'd be glad to implement it.

OK, I will think about it and post here once I will have something that sounds reasonable.

**Comment by matkoniecz** [comment]
So below is my idea dump. I can expand it into pseudocode from the current prose (parts such as tag processing - maybe even outright in a Python code or I can try really lame Rust code).

My initial idea is to have something expandable and relative simple and parametrized. 

Parameters would allow to handle various situations for various maps (for example some places will have massive transit traffic, while have 0 of it). Also, it would allow to spend some time on tweaking parameters for people like me who are not interested in being involved into coding (unfortunately I have no time to get into yet another codebase).

So my idea is that parameters should be in general specified at time of importing the map, but with possibility of overriding them in game to make experimentation easier.

----------

So now to my proposal for less awful random traffic model. Lets call it a proletariat robot model, with following sources of traffic:

 - people go from home to work and later from work to home

and potential expansions:

 - transit traffic incoming from outside and outgoing outside
 - people go from outside of the map to work on the map and later leave the map
 - people leaving map to work and entering map to get back home

It should be possible to later extend it by adding trips to friends/family/school/shops/restaurants/parks/churches/museums/hospitals/etc, people working from home, unemployed, retired, children etc. But lets start from simplified case where everyone works and only works. It is still necessary to setup processing of data to assign population to houses (this will be useful also later ). Note that it will remain useful also in cases where we have population distribution, as we want people to live in houses not in sheds in the garden - so we still need it even if very detailed population density dataset is actually available.

-------------

So what would be necessary for initial "simple" model?

- where people live (based on OSM data and possibly external source)
- sources of workers outside map (parameter of how large this source is - vehicles/hour - initially they may try to enter map without preference for specific roads, just using the least crowded incoming points on borders)
- transit scaling (vehicles/hour, also it may unitially attempt to enter map in any not congested point, with randomly selected exit - maybe weight exit to prefer bigger roads? maybe scale by road class? Parameter for every road?) 

OSM data (if mapped) can provide info where people live and what kind of density can be expected (I can write pseudocode or Python code - it will be based on building area, tags such as `building`, building:use`, `building:levels`, `height`, `ruins` etc). 

OSM data also can provide info where people work - `building`, `office`, `shop`, `craft`, `amenity` etc tags are going to be useful.

It is likely that it will be necessary to randomize part of that in case of missing OSM data and add some random places of work.

Main issue is matching place of work with residence - completely random would be absurd, probably some bias to work closer to home rather farther away would be nice (parameters again!).

-------------

First extension to that model would be modelling rush hour - people go to work and leave to home together. So each employment location would randomize shift time range (potential bonus: possible multiple shifts if that is easy to implement). It would be partially random, potentially partially based on `opening_hours` tags.

**Comment by dabreegster** [comment]
https://github.com/dabreegster/abstreet/commit/ead4a99682d11ec4af4824a1ab4c3854bae7b0d4#diff-2c2c318cdeaacad34869c777e1242d50 is a start. Tried to make the code readable. Lots of improvements possible:

- use better probability distributions to decide departure times and mode choice
- have some background traffic during off-peak times
- maybe add a lunch hour -- go from work to the nearest food-classified building
- Other ideas from above

https://twitter.com/CarlinoDustin/status/1281320152269598720 is the pretty heatmap of people going from a few "businesses" back home.

Marking as a good first issue, since the extensions are pretty bite-sized and pretty creativity-focused.

**Comment by matkoniecz** [comment]
Note to self: https://github.com/dabreegster/abstreet/commit/ead4a99682d11ec4af4824a1ab4c3854bae7b0d4#diff-2c2c318cdeaacad34869c777e1242d50R426 should be easily improvable by accessing OSM tags (that should be available - see https://github.com/dabreegster/abstreet/blob/906a647ade0db027ee07755b17a4a5eb8edf5eda/convert_osm/src/osm_reader.rs#L154 ).

For start, `building=office` also should serve as workplaces.

**Comment by dabreegster** [comment]
Some good ideas coming from https://old.reddit.com/r/Citybound/comments/hoanx4/help_generate_random_people_moving_around_a_city/

**Comment by matkoniecz** [comment]
How can I access osm_tags of a building? I tried obvious `b.osm_tags.get("building")` and I got 

> error[E0609]: no field `osm_tags` on type `&map_model::objects::building::Building`

I tried `grep -nR osm_tags` `grep -nR Building` grepping but nothing obvious appeared.

**Comment by dabreegster** [comment]
You beat me to it; I meant to fix this yesterday. `map_model::Map` doesn't store the building OSM tags to keep file sizes small. We either have to generate the scenario using the `importer` crate, which has access to `RawBuilding` with `osm_tags`, or derive some extra (much smaller) attributes during importing and store those on `Building` for later use. I can quickly put together either approach. What are you computing from the tags? A building type, an estimate on number of people, something else?

**Comment by matkoniecz** [comment]
Building type, number of people.

BTW, it would be useful to have access also to the building area size.

For things that I considered either precomputing resident density and building type of having a full access to tags would be ok.

**Comment by dabreegster** [comment]
The `bldg_types` branch should have all the stub code you need. You can modify the `BuildingType` enum to represent the possibilities. Let me know if anything is unclear.

When you're iterating on this, you only need to do `./import.sh --map --city=krakow`. `--raw` does OSM -> RawMap, but what you're working on doesn't modify this part of the pipeline.

**Comment by matkoniecz** [comment]
> When you're iterating on this, you only need to do ./import.sh --map --city=krakow

Sadly, at least after some changes it is apparently necessary to rebuild also Seattle (`runtime: krakow` is considered as invalid).

**Comment by dabreegster** [comment]
You can workaround this by doing `cargo run --bin game -- data/system/maps/huge_krakow.bin` or similar, forcing it to start with your map.

Since you're changing the map format, running `updater` won't help until I rebuild the maps and upload to Dropbox.

**Comment by matkoniecz** [comment]
One more request: how can I enable buses to be active in this mode? It is not data issue, in "bus only" mode Kraków has some buses cruising around.

**Comment by dabreegster** [comment]
`s.only_seed_buses = None;` right after the `let mut s = Scenario::empty`. I guess I forgot to do that, good catch

**Comment by matkoniecz** [comment]
`s.only_seed_buses = None` is a bit cryptic way to enable buses but it worked :)

**Comment by matkoniecz** [comment]
> You can workaround this by doing cargo run --bin game -- --dev data/system/maps/huge_krakow.bin or similar, forcing it to start with your map. There are more variations documented here.

`cd game; RUST_BACKTRACE=1 cargo run --release -- ../data/system/maps/huge_krakow.bin --disable_block_the_box` I my current command, I have no found way to specify traffic model at start. (though I was not looking really hard)

**Comment by dabreegster** [comment]
>  have no found way to specify traffic model at start

There isn't a way yet except for scenarios expressed as files. The `home_to_work` scenario is created on-the-fly. I'll make a new flag to handle this.

**Comment by matkoniecz** [comment]
Curiously, recently on launch AB was starting from that model (if I specified Kraków map), maybe because it was first in the list?

**Comment by dabreegster** [comment]
Ah you're right, that happens here: https://github.com/dabreegster/abstreet/blob/c2bd5fcf6fcdb970b4d73652084a4068312ca1be/game/src/pregame.rs#L195

If you use the `--dev` flag, the intro screens are skipped. There's not a way currently with that to jump right to the `home_to_work` scenario.

**Comment by matkoniecz** [comment]
Next steps:

offmap trips - https://github.com/dabreegster/abstreet/pull/183#issuecomment-657635867
support museums, more amenities and so on as way to prepare for more varied trips - https://github.com/dabreegster/abstreet/blob/08dc2bbc129db7eb0b44afbc33ff882c1638cbcc/game/src/helpers.rs#L145

**Comment by dabreegster** [comment]
> offmap trips - #183 (comment)

The building blocks should be easy -- you can pick a random inbound border by doing `map.all_incoming_borders().choose(rng).unwrap()`. `SpawnTrip::new` can be passed a `TripEndpoint::Border(intersection_id, None)`. That second param is for an old experiment in Seattle to track more details with trips going out-of-bounds and can be ignored here.

Fair warning: That `amenity_type` classifier was thrown together hastily and without taginfo. Categorizing places is hard. :\

**Comment by matkoniecz** [comment]
> hastily and without taginfo

Good news, it should be easy to improve it :)

Similarly to how this ridiculously simplistic model was a significant improvement :)

**Comment by dabreegster** [comment]
By the way, https://github.com/dabreegster/abstreet/issues/9#issuecomment-660698092 is a new tool to visualize a Scenario. Could be useful for sanity checking the output of this issue's algorithm.

**Comment by matkoniecz** [comment]
I noticed it, sadly automatic segmentation of areas in Kraków is quite silly (there is one very big area and many small ones, all reports agree that "most of traffic goes to the biggest area").

What kind of makes sense, but is not very helpful.

**Comment by matkoniecz** [comment]
Fun fact: when I tried to run current simulation in Kraków only small part of cars gets assigned parking. I got suspicious and I started looking though aerial images. And I just spotted and mapped some quite big parkings that were so far not mapped.

**Comment by dabreegster** [comment]
Related to that, any opinion on #175? Happen to know if there are standards in Krakow for number of private parking spots for different types of houses, apartments, offices?

**Comment by dabreegster** [comment]
Yesterday we had a hackathon and worked on generalizing the P.R. model. I'm going to close this issue in favor of #424, where we'll flesh out and clean up the general approach, which is close to what https://github.com/dabreegster/abstreet/issues/154#issuecomment-656081196 describes
