### ISSUE TITLE
Building from source on Windows

### ISSUE THREAD

**Issue by jvolker** [dabreegster/abstreet#157]
Seems like the Developer guide is missing info for Windows.

When running `cargo run --bin updater.` I got this error:
 ```
error: linker `link.exe` not found
  |
  = note: Das System kann die angegebene Datei nicht finden. (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option
```
Installing [Visual Studio 2019](https://visualstudio.microsoft.com/de/downloads/) worked for me.

Then running the game `cd game; RUST_BACKTRACE=1 cargo run --release` I got: 
`Das System kann den angegebenen Pfad nicht finden.` German for: System can't find path.

Doing this on Windows instead worked for me: 

`cd game && set RUST_BACKTRACE=1 && cargo run --release`

**Comment by dabreegster** [comment]
The first problem: This seems like an issue with the Rust installation process in general, at https://www.rust-lang.org/tools/install. I actually don't see the Windows instructions here; I'll try spoofing my user agent and pretend to be a windows machine in a minute.

The second problem: Just made this easier with https://github.com/dabreegster/abstreet/commit/6919c24bf8a76e8dc2da09d94c8a9548b4490340. Before, you had to ensure that `../data/` existed when you ran the game. Now it'll detect the data dir either in the current directory or one level up. I think the first 3 steps in `docs/dev.md` have always been correct; it's just easy to miss running from the proper directory.

**Comment by jvolker** [comment]
The first problem: As mentioned above

> Installing Visual Studio 2019 worked for me.

The second problem: Thanks for making this easier. And I double-checked and no matter what directory I'm doing this from I get the error. Also `RUST_BACKTRACE=1` as before the cargo command throws `Der Befehl "RUST_BACKTRACE" ist entweder falsch geschrieben order konnte nicht gefunden werden.`

**Comment by dabreegster** [comment]
Ah, I understand now; Windows has a different syntax for setting env variables. Thanks! I'll fix the docs.

**Comment by jvolker** [comment]
Thanks for fixing this.
