### ISSUE TITLE
Crash when clicked on another part of Seattle map

### ISSUE THREAD

**Issue by yurivict** [dabreegster/abstreet#160]
```
<...skipped...>
Read /usr/local/share/abstreet/system/cities/seattle.bin (1)... 0.0236s
switch map...
thread 'main' panicked at 'Creating parent dir failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /usr/ports/games/abstreet/work/abstreet-0.2.2-23-g35768dfb/abstutil/src/io.rs:28:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
switch map took 0.0002s

- switch map took 0.0002s

- switch map took 0.0002s

********************************************************************************
thread 'main' panicked at 'Creating parent dir failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /usr/ports/games/abstreet/work/abstreet-0.2.2-23-g35768dfb/abstutil/src/io.rs:28:5
```

It should never memorize the build directory.

**Comment by dabreegster** [comment]
Ah, we'll need to plumb two parameters actually. `data/system/` is fixed files that're bundled with the game. `data/player/` is where local state is kept -- edits you make, savestates, or (in this case), where your camera was when you left a map. I'll give you a second param to change that directory, so it could be ~/.abstreet or something.

**Comment by dabreegster** [comment]
There's now `ABST_PLAYER_DATA_DIR` as well. Depending how you set this, we might have to do a little more work, like expanding a literal string ~ into /home/$USER. Let me know if that's the case.

**Comment by yurivict** [comment]
Since ```ABST_PLAYER_DATA_DIR``` is a build-time parameter it has to expand ```$USER``` to a user name in a run-time to be usable.
Please default ```ABST_PLAYER_DATA_DIR``` to ```/home/$USER/.abstreet``` and create this directory if it doesn't exist.

**Comment by dabreegster** [comment]
You can set `ABST_PLAYER_HOME_DIR=1` at build-time, then it'll expand to $HOME/.abstreet at runtime. Thanks for the patience!

**Comment by yurivict** [comment]
Thank you!
