### ISSUE TITLE
Mac bug: Game does not start

### ISSUE THREAD

**Issue by akgerber** [dabreegster/abstreet#162]
I downloaded the latest binary zip `abstreet_mac_v0_2_2.zip`, extracted it within my Downloads folder, and attempted to run it. It crashed.

This happens either running the binary in a shell or double-clicking on it.

MacBookAir9,1
OSX 10.15.5 

```
➜  abstreet_mac_v0_2_2$ RUST_BACKTRACE=1 game/game
Inner window size is PhysicalSize { width: 1600, height: 1200 }, monitor is PhysicalSize { width: 2880, height: 1800 }, scale factor is 2
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', /Users/runner/runners/2.263.0/work/abstreet/abstreet/ezgui/src/runner.rs:214:21
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_none_failed
   9: ezgui::runner::run
  10: game::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start_internal
  15: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by dabreegster** [comment]
Can you run `play_abstreet.sh`? Or from terminal, be sure to execute the binary while your current directory is `game/`. In the released version, it looks for the `../data/` directory and is very particular about where you start it. I finally fixed this problem today, so you could run the binary from anywhere, but that's not packed in a release yet

**Comment by akgerber** [comment]
Nice, running that shell script works for me. I just went looking for a binary & tried to run that to start, but guess that was the wrong move.

**Comment by dabreegster** [comment]
Great! I'll close this bug then. By next Sunday, running the executable will also work.
