### ISSUE TITLE
opening settings crashes game - thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', abstreet/ezgui/src/widgets/dropdown.rs:27:27

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#163]
May be related to fact that I added a new map

https://gist.github.com/matkoniecz/a45aab4ce4ca8fa4930e1e2eb7a5648e

**Comment by dabreegster** [comment]
Your monitor's scale factor was one I hadn't seen before, so there was a dropdown menu that broke.

Also, I just broke the serialized map format, so you'll have to re-import again. The error message if you don't should hopefully be clear. Sorry for the hassle, I'll try to limit to one breaking format change a day. :)  (I'm trying to compress the representation more, so it's easier to fit more cities by default in the release)

**Comment by matkoniecz** [comment]
Re-import will not be a trouble, as for ABstreets my next step is anyway mapping. I want to fix broken/missing OSM data that I found while I was testing it :)

**Comment by dabreegster** [comment]
Awesome! That's one use of it that I was really hoping would catch on.
