### ISSUE TITLE
supporting more tags indicating lane layout

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#168]
I made the first pass over https://github.com/dabreegster/abstreet/blob/master/map_model/src/make/initial/lane_specs.rs and my initial question is what kind of tag popularity is needed to include it?

1000 worldwide? 10 000  worldwide? 100 worldwide? Any use in area where someone works on map?

Anyway, I want to suggest https://taginfo.openstreetmap.org/keys/psv%3Alanes#overview that can be reduced to bus lanes (taxis etc are not modeled at all for now from what I have seen)

And https://taginfo.openstreetmap.org/keys/cycleway%3Aboth#values that can be aliased to `cycleway`

(I have looked through this single function, I have not made tests - maybe for example `cycleway:both` is aliased somewhere already?)

**Comment by dabreegster** [comment]
> what kind of tag popularity is needed to include it?

Any use in an area someone's interested in using with A/B Street. A general scheme working anywhere in the world would be great long-term, but it's impractical short-term, so I'm prioritizing based on places people are interested in.

I'll look into mapping `psv` as `LaneType::Bus` and `cycle:both`. One of the easier ways to see if anywhere in the codebase handles a tag is to just grep the code. There's a script to do this and ignore compiled Rust files: `./rgrep.sh cycleway`

**Comment by matkoniecz** [comment]
> Any use in an area someone's interested in using with A/B Street.

Then I want to mention that `psv:lanes` has some use in Kraków (and it will increase once I will start mapping bus lanes that also allow taxis and so on) http://overpass-turbo.eu/s/VVK

`cycleway:both` - is in Seattle http://overpass-turbo.eu/s/VVL (and even more with null value indicating lack of cycleway)

**Comment by dabreegster** [comment]
I think both of these are now working, so closing this bug.
