### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by tomlankhorst** [dabreegster/abstreet#17]
pre-build Linux binaries
 v0.1.18
 7ca08df
```
$ ./play_abstreet.sh
./play_abstreet.sh: line 4:  4080 Floating point exception(core dumped) RUST_BACKTRACE=1 ./game --rng_seed=42
``` 
Ubuntu 18.04.3 LTS
5.0.0-37-generic
i7-7700HQ

Building from source works fine.

**Comment by mdesantis** [comment]
It affects me too

**Comment by dabreegster** [comment]
Weird. I'm running Ubuntu 18.04.3 as well with 4.15.0-1064-oem (a preinstalled Dell kernel). I'm using https://github.com/rust-embedded/cross to cross-compile to Windows, so there's probably a generic x86_64 target. I'll look into this.

**Comment by pmontrasio** [comment]
Ubuntu 19.10, same problem.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

$ uname -a
Linux connettizb 5.3.0-23-generic #25-Ubuntu SMP Tue Nov 12 09:22:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ ./play_abstreet.sh 
./play_abstreet.sh: line 4: 21879 Floating point exception(core dumped) RUST_BACKTRACE=1 ./game --rng_seed=42
```

I don't have Rust installed so I'm not trying to build from sources.

**Comment by dabreegster** [comment]
I tried the v0.1.18 build on an older Linux laptop, but couldn't repro -- it runs fine.

I built another binary in a Docker container using `cross build --release --target x86_64-unknown-linux-gnu --bin game` -- would you mind trying out https://www.dropbox.com/s/wy02ug5nyf8pxrg/game_x86_64-unknown-linux-gnu?dl=0
If that works, I'll change my build scripts to always use cross. I'm still not sure what the difference is; it's a statically linked binary for x86_64 architecture

**Comment by Servuc** [comment]
Hello,

Your version works fine ;)

**Comment by dabreegster** [comment]
That might be some other bug unrelated to the binary compatibility. Can you send the terminal output?

I'll put out a new build tomorrow, probably using this new method with cross. I also got lots of good hints from https://old.reddit.com/r/rust/comments/eaa8f7/building_compatible_linux_binaries/ that I'll try out. Turns out making one binary that works across different Linux distros, Wayland vs Xorg, libc versions, etc, is kind of tricky.

**Comment by dabreegster** [comment]
Try out https://github.com/dabreegster/abstreet/releases/tag/v0.1.19 if you get a chance

**Comment by Servuc** [comment]
This version is better ! :+1:

**Comment by dabreegster** [comment]
Great, please reopen if anyone has problems
