### ISSUE TITLE
assign random parking lanes if given area has no parking lanes tagged in OSM and amount of parkings is ridiculously low

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#171]
And obviously, loudly complain in log while generating the map

**Comment by dabreegster** [comment]
`convert_osm/src/lib.rs` has some `Options` to customize importing per city -- sounds like it's time to flesh these out more. It'll be a bit tedious to specify these new params by flag to `import.sh --oneshot`, so I think it's time to make Kraków an included extra city (like Austin). Is the boundary in `data/other_polygons` the one you'd like to use for now? We can also split into multiple regions if this map has been too slow to load for you.

**Comment by matkoniecz** [comment]
> I think it's time to make Kraków an included extra city

Depends on what that implies - currently it is not really playable (and once #154 is fixed it will in turn be too large to be playable - I am not sure yet what kind of size will be optimal to represent it well and to be usable).

Also, without #141 (trams) I think it is hard to say that it is representing it at all.

But if it is OK to include areas that are not yet playable and missing major features, then it would be OK.

> It'll be a bit tedious to specify these new params by flag to import.sh --oneshot

```
$ cat krakow_import.sh 
./clean_import.sh --oneshot=/home/mateusz/Downloads/abstreet/import_data/krakow.osm

$ cat clean_import.sh 
#!/bin/bash

RUST_BACKTRACE=1 cargo run --release --manifest-path importer/Cargo.toml scenarios $@;
```

**Comment by dabreegster** [comment]
I've added Krakow as an optional map; it'll make it easier for me to iterate on changes affecting it. I'd recommend using the new way of rebuilding it locally:

`./import.sh --raw --map --city=krakow`

The .osm from geofabrik will be cached. If you want to download it again (or augment it with osmupdate), then `rm data/input/krakow/osm*` and rerun the `--raw` stage.

> But if it is OK to include areas that are not yet playable and missing major features, then it would be OK.

Most of the Seattle maps have major problems too. :)  Krakow is an optional map, so somebody has to follow [this](https://github.com/dabreegster/abstreet/blob/master/docs/dev.md#downloading-more-cities) to get it.


I don't want to add `--oneshot_onstreet_parking=...` and so on for every customization. When somebody wants to start customizing an imported city, they're at least committed to playing around enough for me to set up the config for an optional city.
