### ISSUE TITLE
use loading screen space

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#180]
There are some loading/waiting screens (starting map, applying changes, rerunning simulation).

I think that it is an ideal space to display tips, credits, suggestions, "you can get involved" - user is waiting anyway.

**Comment by dabreegster** [comment]
An idea I've never written down anywhere: Styling the loading screen as a crosswalk timer would be cute

**Comment by dabreegster** [comment]
![Screenshot from 2020-09-20 13-03-15](https://user-images.githubusercontent.com/1664407/93720976-bc5ed900-fb41-11ea-981b-4ec522f7c7cf.png)
