### ISSUE TITLE
Crash - thread 'main' panicked at 'PL with total length 4.8312m and 4 pts has ~dupe adjacent pts

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#182]
thread 'main' panicked at 'PL with total length 4.8312m and 4 pts has ~dupe adjacent pts: [Pt2D { inner_x: 2375.9955, inner_y: 2558.916 }, Pt2D { inner_x: 2378.1379, inner_y: 2554.6117 }, Pt2D { inner_x: 2378.1339, inner_y: 2554.6069 }, Pt2D { inner_x: 2378.1461, inner_y: 2554.595 }]', geom/src/polyline.rs:37:13

Happened in game with binaries generated with a modified code, feel free to ignore if reason for crash is not clear and may be related to mapgen building modifications

https://gist.github.com/matkoniecz/eeef801bcf23e8bafe7bec307cdabb99

**Comment by dabreegster** [comment]
Definitely unrelated to your code. There are a few issues like this. I need to do a big refactor and be much more careful about geometry routines that may fail.

**Comment by dabreegster** [comment]
I overhauled lots of the base geometry code. Lots of crashes should either be avoided now or have much more useful debug info. Closing this bug for now; please send the new log when you encounter it again.
