### ISSUE TITLE
Vehicles entering crossing only when previous one left is not matching reality

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#185]
Is it intended behavior, temporary state or intended as permanent?

Because it result in drastic reduction of throughput on crossings, especially large ones.

**Comment by dabreegster** [comment]
Temporary bug. You could try running with the flag `--disable_block_the_box`. There's also a way to override it for individual intersections in `allow_block_the_box`.

I did some work yesterday to make vehicles ignore red lights if they start a sequence of turns through a group of adjacent traffic signals. This helps quite a bit with this general problem. I still need to update this to handle the "don't start a turn unless there's room" checks to better handle the short roads case.

**Comment by matkoniecz** [comment]
note to self and others: `cd game; RUST_BACKTRACE=1 cargo run --release -- --disable_block_the_box` ("All the arguments following the two dashes (`--`) are passed to the binary to run.")

**Comment by dabreegster** [comment]
Consolidating gridlock bugs in #114
