### ISSUE TITLE
link skipped relation ids/urls

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#186]
Log has currently entries such as `Skipping route Bus 109 with 1 sub-routes`

I would be useful to 

(a) explain why it was skipped (some get explanation such as "unknown type")
(b) mention relation id or link it outright with format `https://www.openstreetmap.org/relation/$ID`

**Comment by dabreegster** [comment]
An example skipped one: https://www.openstreetmap.org/relation/10534010
The master relation has 3 routes. Right now I'm only handling cases with 2 routes, and I'm trying to glue them together in a loop. Many assumptions are wrong. :) #190 is also where we can figure out what 3 sub-routes means.
