### ISSUE TITLE
Austin data has disappeared?

### ISSUE THREAD

**Issue by yurivict** [dabreegster/abstreet#192]
Last week https://github.com/dabreegster/abstreet/blob/master/docs/dev.md#getting-started said that opting into everything is:
```
runtime: seattle,huge_seattle,austin
input: seattle,huge_seattle,austin
```

Now it says:
```
runtime: seattle,huge_seattle,krakow
input: seattle,huge_seattle,krakow
```

Did Austin disappear?

**Comment by dabreegster** [comment]
Yes. I originally included Austin just to make sure all of the importing pipeline worked for a second city. There was no active use of Austin by anyone. Now that @matkoniecz is iterating on Kraków, Austin is just a bit of a maintenance burden. At some point, there'll be many cities maintained, but until that point, it's slowing me down a bit for no good reason. Is it OK to exclude it from the FreeBSD release?

I would also not recommend including `huge_seattle` either; I don't regularly test it yet, and even just loading it may oomph your system's RAM a bit much.

**Comment by yurivict** [comment]
Ok, thanks, I'll exclude ```huge_seattle``` then.
