### ISSUE TITLE
convert_osm: Potential out of range panicing

### ISSUE THREAD

**Issue by Fullstop000** [dabreegster/abstreet#2]
https://github.com/dabreegster/abstreet/blob/03b685673bebbc95e2bcbd7c85358547bcffe8c3/convert_osm/src/remove_disconnected.rs#L43-L46

The partitions could be empty if all the roads are filtered by `clip_map`

**Comment by dabreegster** [comment]
True. If all the roads are clipped out, it'd be better to bail out a little earlier than this. Do you have an example .osm and clipping polygon that hits this? I'd like to add in a better error somewhere else.

**Comment by Fullstop000** [comment]
I found this by manually altering my `city.poly` to not match the .osm. Maybe a more specific error is better.
