### ISSUE TITLE
Integrate A/B Street traffic mechanics into Citybound

### ISSUE THREAD

**Issue by brylie** [dabreegster/abstreet#20]
The Citybound game, written in Rust, has the goal of building a realistic city simulation.

https://github.com/citybound/citybound

This A/B Street traffic simulation would be an excellent complement to Citybound. Please consider combining your work so that both projects can benefit.

**Comment by dabreegster** [comment]
Previous discussion at https://old.reddit.com/r/Citybound/comments/cw97zp/ab_street_a_traffic_simulation_game/. Citybound's road editor is quite nice -- a first collaboration might be importing maps into Citybound.

**Comment by dabreegster** [comment]
Citybound doesn't seem to be under active development, and this issue isn't really actionable. Closing it until there's something concrete to do; I'm very open to collaboration.

**Comment by brylie** [comment]
Thanks for your follow-up @dabreegster
