### ISSUE TITLE
intepret highway=service with access=no/private and psv=yes as bus-lane only road

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#203]
See https://www.openstreetmap.org/way/149941587#map=18/50.05730/19.94613

Skipping such roads is (I suspect) reason for `Skipping route Bus 484: Prądnik Czerwony => Swoszowice Poczta (https://www.openstreetmap.org/relation/7734584): couldn't match stop Starowiślna: Lane #6516 isn't near a {Bus, Driving} lane
`

**Comment by dabreegster** [comment]
Fix incoming to include this bus-only service road. The issue with 484 was that https://www.openstreetmap.org/way/233991667 isn't recognized yet, so the pedestrian position snapped to Starowiślna near the Carrefour. I think first we need to get #161 working, then improve the stop/platform matching.
