### ISSUE TITLE
Explain what went wrong with interesection spawning

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#206]
> Alert at 02:10:38.4 (Intersection(IntersectionID(682))): Person 583 couldn't spawn at border Intersection #682, just aborting

An I have no idea is it problem with my transit code, AB, OSM data or something else because there is no hint what went wrong.

**Comment by dabreegster** [comment]
This case is probably no sidewalks there, but yeah, better errors wouldn't be tough. Will fix soon
