### ISSUE TITLE
Surprising "No path between"

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#209]
> Skipping route Bus 105: Cmentarz Batowice => Dworzec Główny Zachód (https://www.openstreetmap.org/relation/3554806): No path between stop on OriginalRoad(https://www.openstreetmap.org/way/339315233 from https://www.openstreetmap.org/node/2486969494 to https://www.openstreetmap.org/node/2486969492) and OriginalRoad(https://www.openstreetmap.org/way/339315234 from https://www.openstreetmap.org/node/2486969492 to https://www.openstreetmap.org/node/264110911). PathRequest(0m along Lane #7536... to 15.7705m along Lane #7542 for Bus)

Both in simulation and in OSM data looks perfectly fine.

**Comment by dabreegster** [comment]
![Screenshot from 2020-08-03 14-49-09](https://user-images.githubusercontent.com/1664407/89230626-82894180-d598-11ea-8fee-405117c3c549.png)
Parts of these roads are clipped out. I think there's nothing the importer could do better here. If you'd like to adjust the existing polygon, or make a few partly overlapping ones for Kraków, send polygons from geojson.io please

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/#map=19/50.07886/19.94907 https://www.openstreetmap.org/#map=19/50.07851/19.95033 probably should be two additional points on boundaries

I will later p[en a new issue with http://geojson.io/#map=2/20.0/0.0 output
