### ISSUE TITLE
osm-xml fails for overpass exports

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#212]
I tried to import tiny area (`50.070,19.933,50.076,19.939`) with oneshot import. Import failed, I think due to error listed below.

https://overpass-turbo.eu/s/WgK

```
  [timeout:1250];
  (
    nwr(50.070,19.933,50.076,19.939);
  );
  out body;
  >;
  out skel qt;
```

Nonrecursive call used to obtain data

```
  [timeout:1250];
  (
    nwr(50.070,19.933,50.076,19.939);
  );
  out meta;
```

also failed, but with a different error.

```
thread 'main' panicked at 'assertion failed: !borders.is_empty()', map_model/src/objects/zone.rs:145:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: std::panicking::begin_panic
  12: map_model::objects::zone::Zone::make_all
  13: map_model::make::<impl map_model::Map>::create_from_raw
  14: importer::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  17: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  18: std::panicking::try
             at src/libstd/panicking.rs:274
  19: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  20: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  21: main
  22: __libc_start_main
  23: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by dabreegster** [comment]
I ran the first query, exported as raw OSM data, but then got `XmlParseError(Error { pos: 1:1, kind: Syntax("Unexpected characters outside the root element: \u{feff}") })`. I don't see the odd unicode character. How did you export?

**Comment by matkoniecz** [comment]
OSM file and ruby scripts are here, in a temporary repo: https://github.com/matkoniecz/tmp

**Comment by dabreegster** [comment]
![Screenshot from 2020-07-20 09-56-26](https://user-images.githubusercontent.com/1664407/87964593-4e2d6580-ca6f-11ea-9a38-4b8b06b0bb02.png)

Something went quite wrong, because this is all the map has. Looking into it.

**Comment by dabreegster** [comment]
![Screenshot from 2020-07-20 10-01-06](https://user-images.githubusercontent.com/1664407/87965018-f2afa780-ca6f-11ea-80ba-db2dabded886.png)

There are almost no roads here. The few that remain are disconnected.

Looking into https://www.openstreetmap.org/way/93153503 as an example. It looks fine. From print debugging, when we process this way, the tags are empty! They look fine in the .xml. Did parsing somehow mess up?

**Comment by dabreegster** [comment]
`Way { id: 93153503, tags: [], nodes: [Node(264111785), Node(1079902552), Node(1079902595), Node(1079902645), Node(1079902669), Node(1079902561)] }` is what https://crates.io/crates/osm-xml parsed. All the tags are missing.

There's some bug in `osm-xml`. I can look into it later. In the meantime, it's possible that something about the overpass XML is strange.

**Comment by matkoniecz** [comment]
> In the meantime, it's possible that something about the overpass XML is strange.

I guess that it can be verified by downloading the same area with JOSM or extracting from Geofabrik dumps. I can add JOSM download file to repo if that would be useful.

**Comment by matkoniecz** [comment]
> Looking into https://www.openstreetmap.org/way/93153503 as an example. It looks fine. From print debugging, when we process this way, the tags are empty! They look fine in the .xml. Did parsing somehow mess up?

And XML file seems perfectly fine...

```
<way id="93153503">
<nd ref="264111785"/>
<nd ref="1079902552"/>
<nd ref="1079902595"/>
<nd ref="1079902645"/>
<nd ref="1079902669"/>
<nd ref="1079902561"/>
<tag k="cycleway" v="no"/>
<tag k="dual_carriageway" v="yes"/>
<tag k="highway" v="residential"/>
<tag k="lanes" v="1"/>
<tag k="lit" v="yes"/>
<tag k="maxspeed:type" v="PL:urban"/>
<tag k="name" v="Kamienna"/>
<tag k="oneway" v="yes"/>
<tag k="parking:lane:both" v="no_stopping"/>
<tag k="sidewalk" v="separate"/>
<tag k="surface" v="asphalt"/>
</way>
```

**Comment by dabreegster** [comment]
Yeah, the XML file looks fine to me. I'm not sure what's wrong. I don't think adding a JOSM export would help that much; it's pretty clear the overpass XML is fine, but isn't parsing right.

I'll likely switch away from `osm-xml` entirely. Its API has always been kind of awkward (there's a `get_members` in `convert_osm` to dance around it). I'd love more type safety, with better prettyprinted URLs -- you could have a `OsmNodeID(usize)` wrapper that prints the URL by default. The crate isn't lots of code, so putting something better together wouldn't be hard. Also worth shopping around other OSM parsing crates.

**Comment by dabreegster** [comment]
I found the problem with your .osm. Look for way 93153503. It first appears just fine, with 6 node references and some tags. But then at the end of the file, it appears again, only with the node references and no tags. That second one overrides the first. This file violates https://wiki.openstreetmap.org/wiki/OSM_XML#Certainties_and_Uncertainties; there shouldn't be any ways after the block of relations.

I could make the parser deal with this, but I'm really curious why overpass is exporting invalid OSM according to the wiki.

**Comment by matkoniecz** [comment]
Oh right, I remember this. 

It sounds like a similar case to https://github.com/drolbr/Overpass-API/issues/265 (overpass by default emits invalid XML, it was closed as wontfix as with special handling it can be forced to work properly)

**Comment by dabreegster** [comment]
Ah that makes sense, overpass emits objects in whatever order you ask for. So would you want the parser in abstreet to handle this too? How do you determine which version of a way is best? The first one wins? Or the one with non-empty tags?

**Comment by matkoniecz** [comment]
I would be fine with parser crashing and explaining why.

Taking first way, taking first way with tags (potentially also complaining) is also fine.

**Comment by dabreegster** [comment]
I made it keep the first valid way, and with that, many more roads made it in. But they must have been disconnected or had something funny going on, because there were still none in the final clip. I tried opening the file in josm to debug, but it broke because it expects a `version`. I don't have a great way of understanding this file, so giving up. If you hit other cases where (valid) overpass exports have issues, please reopen
