### ISSUE TITLE
seed_data.zip is missing signal_single.json

### ISSUE THREAD

**Issue by xoob** [dabreegster/abstreet#22]
I'm running a dev build and the Traffic Lights tutorial crashes because it's missing `data/system/synthetic_maps/signal_single.json`. That's after running `./data/grab_seed_data.sh` which removes the file and overwrites it from a ZIP file that doesn't include the synthetic maps it seems.

**Comment by dabreegster** [comment]
Woops. Uploading a new package, but in the meantime, you could run 'git checkout .' after grab_seed_data.sh to restore the file, since that one's under version control.

I'll think about better ways to keep this up to date.

**Comment by xoob** [comment]
Yep that fixed it! 👍

**Comment by dabreegster** [comment]
The new .zip is uploaded, so closing this
