### ISSUE TITLE
Cyclists want to finish/start trip in the middle of dual carriageway

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#221]
Why they try to do that? It has no connected driveway anyway. And mentioned buildings - like 3581 - are far away.

![screen05](https://user-images.githubusercontent.com/899988/88170921-c4bc9580-cc1e-11ea-9bbc-d20f74fcd5ff.png)

**Comment by dabreegster** [comment]
This is indeed causing lots of problems in Berlin. It's a combination of a few problems. There's a concept of [parking blackhole](https://github.com/dabreegster/abstreet/blob/master/docs/articles/map/article.md) that also applies to bikes starting/ending trips for reasons of not implementing anything better yet. And that redirect doesn't understand roads without sidewalks.

Some of this is covered by #176. I'll see if there's a quick fix for this particular problem.
