### ISSUE TITLE
Transport mode choice 

### ISSUE THREAD

**Issue by jvolker** [dabreegster/abstreet#227]
https://github.com/dabreegster/abstreet/blob/38b8557c82dfa25b818af97db3430b1b9cb7ec5a/sim/src/make/generator.rs#L404

Shouldn't it rather be the following?
```
    if distance < Distance::miles(0.5) {
        return TripMode::Walk;
    }

    if distance < Distance::miles(3.0) {
        if rng.gen_bool(0.15) {
            return TripMode::Bike;
        }
        if rng.gen_bool(0.05) {
            return TripMode::Walk;
        }
    }

    // all trips longer than 3.0 miles

    if rng.gen_bool(0.005) {
        // low chance for really, really dedicated cyclists
        return TripMode::Bike;
    }
    if rng.gen_bool(0.3) {
        // try transit if available, will
        // degrade into walk if not available
        return TripMode::Transit;
    }
    TripMode::Drive
```

As mentioned [here](https://github.com/dabreegster/abstreet/issues/119#issuecomment-662582348) the numbers might need adjustment too.

**Comment by matkoniecz** [comment]
> Shouldn't it rather be the following?

I will compare both version once I have access to a real screen. But what is supposed to be improved here? Behaviour? Code style?

> As mentioned here the numbers might need adjustment too.

Certainly. If you have either specific ideas (or even better, a pull request) then it is highly welcomed.

**Comment by jvolker** [comment]
> But what is supposed to be improved here? Behaviour? Code style?

I guess I was finding it hard to understand the pattern or to describe it with words. It looked to me like some lines got into the wrong place. Basically, if those lines are meant to apply to all trips longer than 3 miles they should come after the 0.5 and 3 miles if-clauses, I think.
   ```
 if rng.gen_bool(0.005) {
        // low chance for really, really dedicated cyclists
        return TripMode::Bike;
    }
    if rng.gen_bool(0.3) {
        // try transit if available, will
        // degrade into walk if not available
        return TripMode::Transit;
    }
```

But as you've mentioned before I understand that this is not fine-tuned yet. 

I'll post here if we've got some data for this or have other ideas for improvments.

**Comment by dabreegster** [comment]
Cleaning up inactiveish bugs. I restructured the code to hopefully be more clear. If there are any other ideas for steps forward here, feel free to reopen
