### ISSUE TITLE
prebaked results missing, what I should do?

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#238]
`WARNING: Missing or corrupt prebaked results for random people going to/from work on huge_krakow, some stuff might break`

I am not sure how to get rid of that and whatever this message appeared earlier.

**Comment by dabreegster** [comment]
The slightly longer explanation: In the optimize commute challenge mode, a particular scenario on a map is run. The player is supposed to make things better. "Better" is relative to that scenario running without any map edits. It'd be expensive and confusing to run two simulations at the same time to compare trip times, so an offline tool "prebakes" the results by running the scenario with no edits, then saving `Analytics` from the simulation to a file.

It doesn't make sense to prebake results for the home->work scenarios until we have some confidence that they're kind of reasonable. Also can't prebake until we can successfully run the full day without gridlock. ;)
