### ISSUE TITLE
tooltip missing for active trip summary

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#239]
Previously it was clear to me, now I see some sitting person icon. I hoped for explanation tooltip on hover but it has failed to explain anything.

**Comment by dabreegster** [comment]
![Screenshot from 2020-07-24 18-15-19](https://user-images.githubusercontent.com/1664407/88445743-a4850600-cdd9-11ea-86c7-2edb52b88458.png)

Been meaning to ask Yuwen for advice here. "Active trips" is a slight misnomer, it's active agents moving around the map. (So if someone's doing a driving trip but they're currently walking to their car, it counts as a pedestrian.)

You might want to know how many buses+trains are running. That's separate from the number of current public transit passengers. That last icon is supposed to be transit riders. Tooltips would certainly help, but maybe there's a more clear icon. Any ideas?
