### ISSUE TITLE
looping service road is skipped, as result parking gets low capacity

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#242]
https://www.openstreetmap.org/way/60420319

I remember seeing code somewhere that deliberately throws out looping roads.

**Comment by dabreegster** [comment]
https://github.com/dabreegster/abstreet/blob/fc761ae0325c2a553201af4b8abf98c881d6a0d2/map_model/src/make/buildings.rs#L237

Geometry is hard. Trying to extract the loops and use them, but it fails sometimes. I'll see if this example reveals some problem in https://github.com/dabreegster/abstreet/blob/fc761ae0325c2a553201af4b8abf98c881d6a0d2/geom/src/polygon.rs#L312

**Comment by matkoniecz** [comment]
Thanks, it is really great to have this notifications about issues getting fixed :)

Let me know once valuable bug report will be fixed and only ones that are unlikely to be fixed are left (due to them being overly specific or with low ROI or blocked by other issues). Then I can look for some additional stuff being broken :)

(I have plans to submit more code but I admit that it is in category of vague plans and classified as entertaiment)

**Comment by dabreegster** [comment]
> Let me know once valuable bug report will be fixed and only ones that are unlikely to be fixed are left 

All the open issues you've filed are still valuable (good ROI), I'd say most are just blocked / I haven't hit the right mood to attempt them yet. Separate footways, cycleways, trams, etc all need some kind of generalized snapping. Things like #150 and #145 are easier, I'll consider them for warmup tasks this week. #156, #180, and #239 might be blocked another month or so till our UX expert finishes her internship and can give advice again. Feel free to keep submitting bugs if you find more things broken, but I also understand if you'd prefer to wait for more of the current round to be fixed first.
