### ISSUE TITLE
Windows crash while doing random actions

### ISSUE THREAD

**Issue by babastienne** [dabreegster/abstreet#249]
Hey there,

I tried your software and while using it on windows platform I randomly get some crashes while performing random actions. This usually happens after only few minutes (less than 5) after launching the game.

This is the stack trace I get when looking at the output.txt file : 

```thread 'main' panicked at 'internal error: entered unreachable code', game\src\sandbox\gameplay\freeform.rs:279:22
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: DefSubclassProc
  19: DefSubclassProc
  20: CallWindowProcW
  21: CallWindowProcW
  22: glPushClientAttrib
  23: CallWindowProcW
  24: DispatchMessageW
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: BaseThreadInitThunk
  34: RtlUserThreadStart
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.

******************************************************************************
Wrote ../data/player/camera_state/huge_krakow.json
Crash! Please report to https://github.com/dabreegster/abstreet/issues/ and include all output.txt; at least everything starting from the stack trace above!

At 00:00:13.8

Camera:
{ "cam_x": 1469.7931060265569, "cam_y": 2254.0628884685184, "cam_zoom": 1.2203801245971941 }

No edits

Crash! Please report to https://github.com/dabreegster/abstreet/issues/ and include all output.txt; at least everything above here until the start of the report!
******************************************************************************```

**Comment by dabreegster** [comment]
Hi,

Unfortunately the stack trace on Windows doesn't have anything useful in it. Could you pinpoint any particular action you take that causes a crash?

If you're using the 0.2.5 build and are using the autocomplete for road names (hotkey **k**) or clicking an item on a dropdown menu, that's a bug I noticed just after the release and fixed Monday. Since lots of people will likely hit this, I'll put out an updated build in the next hour or so.

**Comment by dabreegster** [comment]
Please try [0.2.5a](https://github.com/dabreegster/abstreet/releases/download/v0.2.5/abstreet_windows_v0_2_5a.zip) instead. I suspect the crashes you hit are fixed. If you find another one, let me know!
