### ISSUE TITLE
importer failed when two roads wind up with the same polyline

### ISSUE THREAD

**Issue by Blazar221** [dabreegster/abstreet#256]
find each intersection polygon: 1,523/19,762... 0.2001sthread 'main' panicked at 'OriginalRoad(https://www.openstreetmap.org/way/311991084 from https://www.openstreetmap.org/node/1530629361 to https://www.openstreetmap.org/node/7140285984) and OriginalRoad(https://www.openstreetmap.org/way/342923731 from https://www.openstreetmap.org/node/1530629361 to https://www.openstreetmap.org/node/7140285984) wind up with the same polyline', map_model\src\make\initial\geometry.rs:130:17

I check the map on openstreetmap.org, but cannot figure out why these two roads are special

**Comment by dabreegster** [comment]
![Screenshot from 2020-07-31 08-47-57](https://user-images.githubusercontent.com/1664407/89052495-a3d4fe00-d30a-11ea-805d-b1845a07ee9d.png)

If you click on the two ways, they overlap a little bit in the intersection. If you go into the ID editor on OSM and click between the two ways, you can see it pretty clearly. This is incorrect mapping, and it's better to fix the problem in OSM than attempt some kind of automatic workaround. If the edit you need to make isn't clear, I can try to explain it better or give an example. You need to make the southern residential road and the northern primary one share exactly one node in common, either https://www.openstreetmap.org/node/7140285984 or https://www.openstreetmap.org/node/1530629361. Right now they share two.

**Comment by matkoniecz** [comment]
maybe "ways A and B have overlapping segments" would be more clear and worth including in the error?

**Comment by Blazar221** [comment]
I modified my osm file and this error disappeared. Thanks a lot! I guess I did not pay much attention on the nodes.

**Comment by dabreegster** [comment]
Great! You should make the fix on OSM though; it'll help everyone.
