### ISSUE TITLE
support multistorey parking buildings

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#265]
For example https://www.openstreetmap.org/way/531626145 has multiple times greater capacity than implied by its area - it has 5 levels, including underground one

**Comment by dabreegster** [comment]
`parking:levels` looks super rare: https://taginfo.openstreetmap.org/search?q=parking%3Alevels
I'll add support for `building:levels`, but I'd vote for fixing the few cases of the other one in OSM.

**Comment by matkoniecz** [comment]
`parking:levels` is from "maybe I should promote this tag" category, I thought about it in context of cases where office/mall has 1 or 2 or 3 parking levels.

And yes, `building:levels` should be mapped there, I guess that I need one more trip.

**Comment by dabreegster** [comment]
Woops, I just realized the PR I sent out doesn't actually handle parking attached to buildings at all. I'll send a followup for that.

**Comment by matkoniecz** [comment]
Great! This building is kind of important as it carries significant chunk of parking space in this area (not sure how large, but I expect it to be noticeable given that it has about 150 parking spaces).
