### ISSUE TITLE
The "Developer guide" link in the README is broken

### ISSUE THREAD

**Issue by yurivict** [dabreegster/abstreet#307]
Invalid URL https://dabreegster.github.io/abstreet/howto/dev.html

**Comment by yurivict** [comment]
The "Getting Started" section https://github.com/dabreegster/abstreet/blob/master/docs/dev.md#getting-started is gone.

**Comment by dabreegster** [comment]
Fixed by https://github.com/dabreegster/abstreet/pull/308
