### ISSUE TITLE
CLI options to choose map and scenario at startup

### ISSUE THREAD

**Issue by andrewguertin** [dabreegster/abstreet#31]
It would be nice to have command line options to set the sandbox mode map and scenario at startup, to quickly get back in to the simulation at startup.

Potentially also:
- map
- scenario
- map scroll/zoom
- start simulating
- challenge mode

This would be useful after making code changes, to quickly get back in to simulation, or for automated testing.

**Comment by dabreegster** [comment]
Still unaddressed:

- starting with a camera position. This restores from the last state right now (data/player/camera_state/). Workaround is to use the shortcuts feature -- press the ' key or look for the star icon (currently bottom left from HEAD, but it's moving somewhere else probably).
- starting in challenge mode. Need to come up with a way to address these on the command line sanely, probably just some new field in https://github.com/dabreegster/abstreet/blob/2b6c6b371639b886be53d669ecffc982458bfd19/game/src/challenges.rs#L25
