### ISSUE TITLE
Crash on Start of Challenge Scenario

### ISSUE THREAD

**Issue by extmind** [dabreegster/abstreet#318]
I've downloaded the official v0.2.10 build for Linux and played through the tutorial. But when I try to start the "optimize VIP commute" challenge, the game crashes immediately.

Here's the log: [output.txt](https://github.com/dabreegster/abstreet/files/5189269/output.txt)

**Comment by dabreegster** [comment]
I found this problem right after the release: https://github.com/dabreegster/abstreet/commit/0b9b7e1a65ff5d46db501598c651e4ebfea1192b
I'll put out a patched build by tonight

**Comment by dabreegster** [comment]
https://github.com/dabreegster/abstreet/releases/tag/v0.2.10
Sorry for the hassle!
