### ISSUE TITLE
Can't build on Windows: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by andrewguertin** [dabreegster/abstreet#33]
On https://github.com/dabreegster/abstreet/blob/38bc88d54bcc3716987e67513ab2400efbba9537/game/build.rs#L12, the build script does something for each file, but skips the file "src/helpers.rs". However, on windows the path is "src\\\\helpers.rs", so the file isn't skipped and something down the line fails.

I haven't figured out exactly what fails or why, but adding "src\\\\helpers.rs" to the comparison lets the build complete.

**Comment by dabreegster** [comment]
There are a few other places in the abstutil crate especially that try to do Unixy path things. Let me know if you hit any more problems.

**Comment by andrewguertin** [comment]
Thanks! I'm normally on Linux, just had to use windows while I was home for the holidays, so don't expect too many more windows bugs from me!
