### ISSUE TITLE
Minor UI Issues

### ISSUE THREAD

**Issue by sarahlabianca** [dabreegster/abstreet#34]
![image](https://user-images.githubusercontent.com/26124802/72172082-e6001780-3399-11ea-8b3c-26de1233e037.png)
- Pause button needs to align vertically with the rest of the other buttons
- Area in which pause button is contained needs to be made wider
- Reset text and icon need to be brought down to align vertically with the rest of the buttons

![image](https://user-images.githubusercontent.com/26124802/72172136-0cbe4e00-339a-11ea-8b6a-38a226215b19.png)
- Vertically align buttons

**Comment by dabreegster** [comment]
![speed_panel](https://user-images.githubusercontent.com/1664407/73394558-b2c2f100-4292-11ea-8bfa-2b0cd6b6d1e0.png)
This'll be in this Sunday's build. Thanks for helping me find these problems!
