### ISSUE TITLE
Map not showing on minimap (Windows)

### ISSUE THREAD

**Issue by sarahlabianca** [dabreegster/abstreet#36]
![image](https://user-images.githubusercontent.com/26124802/72173049-4db76200-339c-11ea-92ca-85d4dfb51c8f.png)

The map portion of the minimap is not showing on windows (see attached screenshot)

Running windows 10 pro, x64

**Comment by dabreegster** [comment]
Should be fixed in https://github.com/dabreegster/abstreet/releases/tag/v0.1.24!
