### ISSUE TITLE
Crash when leaving the edit-mode (v 2.15)

### ISSUE THREAD

**Issue by natrius** [dabreegster/abstreet#367]
**OS**

Windows 10

**Game Version**

abstreet_windows_v0_2_15

**Output.txt from game root-folder**

[output.txt](https://github.com/dabreegster/abstreet/files/5376669/output.txt)

I tried it for some time now (quite dumbfold on how to finish :D ) but it crashes from time to time. 

EDIT: It seems like its happening when editing a lane and then getting out of the editing mode.

**Comment by dabreegster** [comment]
Thanks for reporting! It's happening generally when leaving edit mode with any scenario loaded. I introduced the bug last week when making map loading asynchronous for the web. Haven't found a clean way to fix it yet, but this is a very critical bug that'll impact many people. I might yank the 2.15 release. For now, please use https://github.com/dabreegster/abstreet/releases/tag/v0.2.14, sorry for the hassle

**Comment by natrius** [comment]
I should add, its not every time i'm leaving edit mode. It works sometimes. Should i close the issue?

**Comment by dabreegster** [comment]
It's a race condition with the time warp screen that tries to resume the simulation from the time you entered edit mode. You might get lucky sometimes with the order of windowing events that happens. This issue definitely shouldn't be closed yet. :)

By the way, any luck importing Salzburg?

**Comment by natrius** [comment]
Perfekt, i changed the title so its more fitting and hopefully no duplicates will be created. 
(And i found out: at home i can just use 2.14 because there is no Linux-Version for 2.15 ;) ).

Wanted to finish the tutorial first, will try tomorrow the import.

**Comment by dabreegster** [comment]
Woops, there should be a Linux 2.15; the github upload failed. It exists now. I've been travelling, so the release last week was rushed. :(
