### ISSUE TITLE
Web interface freezes in the tutorial when skipping forward to 'task 6'

### ISSUE THREAD

**Issue by Robinlovelace** [dabreegster/abstreet#374]
Reproducible example (seems a bit intermittent): 

1. Click on this link: http://abstreet.s3-website.us-east-2.amazonaws.com/

2. Skip through the tutorial as shown below - it freezes for me. Could it be something to do with my settings? Can try on Google Chrome (tried on a recent version of Firefox).

![Peek 2020-11-02 14-54](https://user-images.githubusercontent.com/1825120/97882602-b4d34800-1d1b-11eb-8ba7-eb3e741bf829.gif)

**Comment by dabreegster** [comment]
The developer console (Ctrl+Shift+I on some browsers) shows the problem:
![Screenshot from 2020-11-02 10-44-52](https://user-images.githubusercontent.com/1664407/97906426-7d06d900-1cf8-11eb-96b2-d5683582dced.png)
https://github.com/dabreegster/abstreet/blob/6e417340e4e068607053de289f98400c95799460/game/src/sandbox/gameplay/tutorial.rs#L604 tries to load a file directly, but on the web, we have to do a more convoluted dance with `game/src/load.rs`. It might be tricky to squish in room for a loading state in the tutorial. @michaelkirk offered to look at this later, and I think it'd be good to get a second opinion on how the async web file loading stuff works at this point. :)

**Comment by michaelkirk** [comment]
I think there's plenty more that can and will be done with async file loading, but this particular issue was fixed in #376 last week.

**Comment by dabreegster** [comment]
Thanks! I'll close this issue; #377 is a reasonable place to track work on async files in general.
