### ISSUE TITLE
Web client is unable to detect screen resizing

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#379]
I enabled browser console during loading, after disabling it I have permament reduction of screen space used by web version of AB.

Not sure is it fixable from within AB or it it an upstream limitation.

**Comment by dabreegster** [comment]
I set `dump_raw_events = true` in `widgetry/src/runner.rs` and manually fiddled with window size. winit doesn't fire any events at all for resizing, opening/closing the developer console, etc. There may be a way to check for screen size changes manually -- https://github.com/rust-windowing/winit/issues/1491. I'll experiment with this later.

**Comment by michaelkirk** [comment]
I can take a look at this!
