### ISSUE TITLE
Would be nice to be able to navigate backwards in menus

### ISSUE THREAD

**Issue by sarahlabianca** [dabreegster/abstreet#40]
It would be nice to be able to navigate backwards in menus
For example, when changing lane types once I have picked a lane type to change I cannot go backwards to change the line type I have picked. I have to esc and then go through the bulk change menu again.

Minor, but would make it a little bit more user friendly.

**Comment by dabreegster** [comment]
All of these sequential menus in the main game (not internal debug modes) have been redesigned completely. Asking one question at a time for things like bulk edit was never even good UX. Thanks for pointing this out as a design issue!
