### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by bjorn3** [dabreegster/abstreet#41]
```
$ cd game
$ cargo run --bin game
HiDPI factor is purportedly 1.5
load map...
upload textures (2)... 0.1244s
2 textures grouped into 2 arrays (with the same dimensions)
Loading map ../data/system/maps/montlake.bin
thread 'main' panicked at 'Couldn't read_binary(../data/system/maps/montlake.bin): No such file or directory (os error 2)', <::std::macros::panic macros>:5:6
```

**Comment by Swoorup** [comment]
https://github.com/dabreegster/abstreet/blob/master/docs/dev.md

Step 2

**Comment by bjorn3** [comment]
Thanks. I didn't expect it to be in the developer readme.

**Comment by dabreegster** [comment]
I added a link to those instructions on the front page, but I'm curious if even the instructions link was easy to spot. What would make it easier to wind up at these pages?

**Comment by Swoorup** [comment]
I see you have already updated the readme by linking, but I guess most people just want to first install without going through a developer specific readme. 
I would have directly put the main installation guide section in the main readme.

**Comment by dabreegster** [comment]
Made some more changes. I don't want to inline the build from source instructions on the main page, since it's so long already and since the steps are slightly unusual (downloading all the input data)
