### ISSUE TITLE
Panicked due to stats

### ISSUE THREAD

**Issue by loleg** [dabreegster/abstreet#42]
```
- reset simulation took 0.0048s
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', geom/src/stats.rs:105:9
```

This happened right after I finished the tutorial. I clicked around in the stats at one point, since I wasn't sure how to finish the last challenge (it would have helped me to know that I'm waiting for all the trips to complete, obvious in retrospect, but an arrow to the top right of the screen would have been a clue). Let me know if you'd like the full trace and `montlake.json`

**Comment by dabreegster** [comment]
I hit this bug too and think I fixed it with https://github.com/dabreegster/abstreet/commit/2daf5c51ca5a8d54c51b78ba0e2756e1d5ba09cc. What commit were you synced to?

I'll make the end condition more clear. Thanks for going through the tutorial -- any parts of it unclear? Anything missing from it -- after finishing it, is sandbox mode or the traffic signal challenge confusing?

**Comment by loleg** [comment]
@dabreegster I was running the v0.1.25 release, because I can't quite figure out how to start from source yet (my Rust experience is still rudimentary).

As far as tutorials go, I thought it was good, but I don't know how to respond to your question. I'd have to go through it again to give you some real feedback :)

**Comment by dabreegster** [comment]
https://github.com/dabreegster/abstreet/releases/tag/v0.1.26 should fix this. The tutorial hasn't changed substantially since the version you ran, so it's probably not worth your time to replay it. Thanks for the report!
