### ISSUE TITLE
Is 2021 roadmap available somewhere?

### ISSUE THREAD

**Issue by matkoniecz** [dabreegster/abstreet#435]
https://github.com/dabreegster/abstreet/search?q=2021+roadmap finds nothing, not at https://github.com/dabreegster/abstreet/projects and not linked from https://github.com/dabreegster/abstreet/releases/tag/0.2.24

I was quite curious in it but I failed to locate it.

**Comment by dabreegster** [comment]
I sent it to your email, feel free to comment. I'm not ready for a wide audience yet. Will post a final public version after discussing with a few people offline.

**Comment by matkoniecz** [comment]
Thanks! I posted some comments, let me know which ones were useful.

Closing as fixed, someone looking for roadmap will likely find it.
