### ISSUE TITLE
'Traffic' is too narrow a description of the scenario selector dropdown menu in the sandbox

### ISSUE THREAD

**Issue by Robinlovelace** [dabreegster/abstreet#453]
My understanding of this menu is that any scenario can be visualised, not just scenarios representing 'traffic':

![image](https://user-images.githubusercontent.com/1825120/104587814-687f7f00-565f-11eb-9ce7-e6f1034f0b79.png)

I think a more realistic, less confusing and precise name would be Scenario.

**Comment by dabreegster** [comment]
Thanks! There's a small followup I'll make to update the button tooltip from "change traffic" to "change scenario."

Originally this was called "scenario", but from some UX testing with a few people, "scenario" wasn't as familiar a term. I also recently discussed with @michaelkirk and @muzlee1113 changing this from a drop-down menu to a full modal pop-up. That'll give more room for explaining what these different choices mean. I'll go ahead and make that new dialog now too.

**Comment by Robinlovelace** [comment]
Great stuff. In case of use to anyone here's the code I used to find the relevant bit of code and make the change, using 2 CLI tools written in Rust:

```
rg Traffic:
sd 'Traffic:' 'Scenario:' $(fd . game/src/sandbox/gameplay)
```
