### ISSUE TITLE
Left arrow keyboard shortcut is ambiguous in Tutorial

### ISSUE THREAD

**Issue by ortem** [dabreegster/abstreet#472]
**Version**: master `2505d64e8b6976ec568bca8097d6e0a938894b53`

When passing the Tutorial, the ← (Left Arrow) key means both "Previous tutorial" and "Slow down". So when I try to slow the speed down, the Tutorial rewinds to the previous step instead. How's about using another shortcut for the "Previous tutorial" action, probably `Ctrl + Left Arrow`?

<img width="507" alt="Screenshot 2021-01-22 at 23 51 39" src="https://user-images.githubusercontent.com/4854600/105545304-f0732200-5d0c-11eb-8f33-1df8a3472f99.png">
<img width="345" alt="Screenshot 2021-01-22 at 23 51 45" src="https://user-images.githubusercontent.com/4854600/105545309-f1a44f00-5d0c-11eb-845c-dd3d749a9855.png">

### Steps to reproduce
1. Open Tutorial
2. Pass some steps
3. Push ← (Left Arrow)
4. The tutorial rewinds to the previous step

**Comment by michaelkirk** [comment]
Thanks for reporting! I'm pretty sure I just broke this with the button overhaul. I'll take a look.

**Comment by ortem** [comment]
@michaelkirk Great! FYI I've just opened another very related issue: https://github.com/dabreegster/abstreet/issues/473

**Comment by michaelkirk** [comment]
Excellent, I've addressed them both in #474 

As I alluded to, I recently made a broad set of changes to the way we build buttons, so it's possible other similar bugs are lurking. Please let us know if you encounter anything else strange.
