### ISSUE TITLE
Wrong icon for "Next tutorial" button

### ISSUE THREAD

**Issue by ortem** [dabreegster/abstreet#473]
**Version**: master `2505d64e8b6976ec568bca8097d6e0a938894b53`

When passing the Tutorial, the icon used for the "Next tutorial" button is incorrect (and the same as the icon for "Previous tutorial" button).

<img width="756" alt="Screenshot 2021-01-22 at 23 50 06" src="https://user-images.githubusercontent.com/4854600/105546180-1e0c9b00-5d0e-11eb-8871-baab5c1395f3.png">

**Comment by michaelkirk** [comment]
Also probably my fault. Taking a look!
