### ISSUE TITLE
X button unclickable on the data form (15 minute neighborhood explorer project)

### ISSUE THREAD

**Issue by GaneshT21** [dabreegster/abstreet#482]
![Xbutton Unclickable](https://user-images.githubusercontent.com/77949520/106087076-38b98800-60f1-11eb-9652-491e36bbdc52.PNG)

**Comment by dabreegster** [comment]
Thanks for reporting! The "X" button in the native version closes the entire application. On the web, it doesn't make sense to close the entire tab.

@michaelkirk removed the equivalent "X" button from the title screen of A/B Street recently, reasoning that people already know how to close a window to exit an application. I can make the same change tomorrow to the 15min app and a few others.
