### ISSUE TITLE
Web tutorial panics when clicking on a car

### ISSUE THREAD

**Issue by artdent** [dabreegster/abstreet#487]
This appears to be 100% reproducible when clicking on any car, but here are the easiest repro steps:
- Visit http://abstreet.s3-website.us-east-2.amazonaws.com/dev/game/ (Chrome 85 mac, if that is relevant)
- Advance to task 5 of the tutorial
- Advance through the instructions dialog and click "Try it!"
- Click on a car
- The game freezes immediately with a panic:
```
Panicked: panicked at 'Can't read ../data/../widgetry/icons/arrow_drop_down.svg: Can't slurp_file ../data/../widgetry/icons/arrow_drop_down.svg, it doesn't exist', abstio/src/lib.rs:28:23
Uncaught RuntimeError: unreachable
game.js:868 Panicked: panicked at 'already mutably borrowed: BorrowError', /home/dabreegster/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/web/event_loop/runner.rs:514:30`
Uncaught RuntimeError: unreachable
```

The js console stack traces are of course not helpful for wasm code, so I apologize if this doesn't end up being easily diagnosable.

**Comment by dabreegster** [comment]
Oh no, I thought the web version _didn't_ have this bug. I fixed it in https://github.com/dabreegster/abstreet/commit/8f0c027bb08d3136c0da24acc8c36e3b7da66882; I'm redeplyoing the web version now. Should be up in a few minutes.

**Comment by dabreegster** [comment]
Fixed in the web version now, thanks for calling my attention to it! In case you try the .zip releases, they have the same bug; I'll push a new build sometime tomorrow. Let me know if you hit any more problems!

**Comment by artdent** [comment]
Amazing. I guess I tried this out at the exact wrong time, or rather the exact right time for noticing the bug. Thank you for the quick fix!!

**Comment by michaelkirk** [comment]
Shoot, that was my bad. Sorry @artdent. Thanks for fixing @dabreegster!
