### ISSUE TITLE
/data/system/maps/montlake.bin is missing or corrupt

### ISSUE THREAD

**Issue by jdturizo** [dabreegster/abstreet#49]
hi, i got a problem trying to run the program, when I run it, the terminal show me this error ./data/system/maps/montlake.bin is missing or corrupt. what does it mean? how can I fix it ?

**Comment by dabreegster** [comment]
It means the version of the code and the version of the data are out-of-sync. Run `git pull` to make sure you have the latest code, and `./data/grab_minimal_seed_data.sh` to get the latest data. https://github.com/dabreegster/abstreet/blob/master/docs/dev.md#getting-started has these steps.

I just tried a fresh install using these instructions and it worked for me. The scripts use relative paths, so make sure to run from the correct directories.

**Comment by dabreegster** [comment]
There's now a more powerful updater tool. https://github.com/dabreegster/abstreet/blob/master/docs/dev.md has new instructions. Please reopen if you're having issues. Thanks!
