### ISSUE TITLE
Target car not visible in tutorial task 5

### ISSUE THREAD

**Issue by daiwai** [dabreegster/abstreet#52]
In task 5 (Escort) of the tutorial. The target car isn't visible for me.

When task 5 starts, I get a few messages like the following in stdout and the arrow points outside the visible area, so the task cannot be completed:

`No room to spawn car for Trip #45 by Person 45. Not retrying!`

and

`Alert at 00:00:00.0 (Person(PersonID(45))): Person 45 had a trip aborted, and their vehicle Car #30 was warped to Offstreet(BuildingID(1956), 0)`

If I change the target car to one that is not mentioned in those messages, i.e. id 8, I can complete the task.

I ran the game with `cargo run` from the `/game` directory (currently on commit 3f48b4bf228f81).

**Comment by dabreegster** [comment]
Thanks for reporting this! I inadvertently broke some of the tutorial this week and meant to fix it up before the binary release tonight. I'll be more careful about breaking changes in master going forward.

**Comment by orpheeantoniadis** [comment]
Still have the issue on the last release (commit 4041ee6d5cea002f22f2661cca5d2618854fd483)

**Comment by dabreegster** [comment]
Sorry, I managed to break it again. A few parts of the tutorial need to be updated now that some cars park inside buildings. I'll try to make the initialization in the tutorials less dependent on these changes.

**Comment by dabreegster** [comment]
Sorry this took so long to fix! I'll make a new binary release tonight including this.
