### ISSUE TITLE
Refactor trip table code

### ISSUE THREAD

**Issue by dabreegster** [dabreegster/abstreet#53]
https://github.com/dabreegster/abstreet/blob/master/game/src/sandbox/dashboards/trip_table.rs

https://github.com/dabreegster/abstreet/blob/master/game/src/sandbox/dashboards/parking_overhead.rs

These share lots of duplicated code. I don't know what the ideal API to construct a table should be -- declare the columns, whether they're sortable, provide all the data in a reasonably type-safe way, etc. A bit complicated by the checkbox filters that're different between the two.

Any ideas? Or an existing crate for heterogeneously typed sortable tables?

**Comment by NickSchimek** [comment]
I will take a look at this.

**Comment by dabreegster** [comment]
![Screenshot from 2020-09-21 13-36-58](https://user-images.githubusercontent.com/1664407/93818697-89831680-fc0f-11ea-8596-fb3961b148cb.png)
Yuwen has some new designs that make the requirements for the table a little more intricate. I'm going to attempt something. @NickSchimek if you made any progress on this, mind sending the branch? Thanks!

**Comment by NickSchimek** [comment]
I have not been able to make progress on this @dabreegster. I tried some new things, but they were not working out. I had another plan to try, but it got side tracked and I haven't made my way back around to this issue.

Please go ahead and attempt something.
