### ISSUE TITLE
Metric seems to extend past the box

### ISSUE THREAD

**Issue by jasikpark** [dabreegster/abstreet#61]
<img width="1680" alt="Screen Shot 2020-06-21 at 10 23 49 PM" src="https://user-images.githubusercontent.com/10626596/85245863-8f017280-b40e-11ea-858d-4cf5d55729d1.png">

**Comment by dabreegster** [comment]
This looks roughly double the size that red line should be. Can you click the settings button in the bottom right and tell me what the **Scale factor** (near the bottom) is set to? We've had lots of problems with Mac Retina displays in the past, but I haven't seen this one before.

**Comment by jasikpark** [comment]
It's set to 2.0
<img width="642" alt="Screen Shot 2020-06-21 at 10 51 31 PM" src="https://user-images.githubusercontent.com/10626596/85246924-c3c2f900-b411-11ea-9563-c18ae100b7e5.png">

**Comment by dabreegster** [comment]
https://github.com/dabreegster/abstreet/suites/824549979/artifacts/9136765 should fix

**Comment by jasikpark** [comment]
great! i’m getting a 404 from that url though...

**Comment by dabreegster** [comment]
Yup, sorry, try the proper release: https://github.com/dabreegster/abstreet/releases/tag/v0.2.0a
Github build artifacts don't seem to be public for long

**Comment by dabreegster** [comment]
I think this is fixed now; please reopen if not
