### ISSUE TITLE
Is there supposed to be a target car shown here? I'm confused at this part.

### ISSUE THREAD

**Issue by jasikpark** [dabreegster/abstreet#62]
<img width="1680" alt="Screen Shot 2020-06-21 at 10 28 04 PM" src="https://user-images.githubusercontent.com/10626596/85245923-b6f0d600-b40e-11ea-8d65-909343dc133e.png">

**Comment by dabreegster** [comment]
Thanks for reporting! There should be an arrow pointing at the first purple car on the north lane (heading southbound). The message box is covering it up. I'm trying to sort out why -- it looks like you're pretty zoomed out in this view, but the camera should be fixed at a certain point here. When the message box closes, could you press **Ctrl+S** to activate dev mode (bottom right corner), then **Ctrl+D** to go to debug mode, then hold your **right Ctrl** key to get a tooltip. Does the last line say zoom about 10.0?

I can do something more clever to ensure the message box doesn't cover up things being pointed to on the map. Working on it.

**Comment by jasikpark** [comment]
ah. I'm on a Macbook Pro and I have 
[ctrl][alt][cmd][space][cmd][alt]

no right ctrl 😅

**Comment by jasikpark** [comment]
would just using [cmd] instead of [ctrl] on macs be the right move? That would certainly put it more in the sphere of regular apps, though idk how much effort that would require

**Comment by dabreegster** [comment]
I have to check how winit handles the command key. (https://github.com/dabreegster/abstreet/blob/e46f118d27308e59aa37175639d8027d728f97c2/ezgui/src/event.rs#L301 has the current mapping I'm using). I can borrow a friend's Macbook tomorrow and try this out; in the meantime, you can hack your way past this part of the tutorial by pretending you know you're supposed to follow at that first purple car. :)

**Comment by jasikpark** [comment]
true, true

Caleb Jasik  
calebjasik@jasik.xyz(mailto:calebjasik@jasik.xyz)
https://jasik.xyz

**Comment by dabreegster** [comment]
https://github.com/dabreegster/abstreet/suites/824549979/artifacts/9136765 should work around this by moving the message box to the left for this piece. Still thinking about a more robust fix

**Comment by dabreegster** [comment]
Actually that link is bad, https://github.com/dabreegster/abstreet/releases/tag/v0.2.0a

**Comment by dabreegster** [comment]
I think this is fixed now; please reopen if not. I switched the debug key to left control for the future
