### ISSUE TITLE
Fails on launch

### ISSUE THREAD

**Issue by brookstalley** [dabreegster/abstreet#63]
Downloaded for windows, unblocked EXE, and output.txt says:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." })', D:\a\abstreet\abstreet\ezgui\src\runner.rs:213:21`

**Comment by dabreegster** [comment]
Argh the Windows build is missing an entire directory. Sorry, give me ~20 mins

**Comment by dabreegster** [comment]
Try https://github.com/dabreegster/abstreet/releases/download/v0.2.0a/abstreet_windows_v0_2_0b.zip
Sorry for the hassle!

**Comment by brookstalley** [comment]
Much better! Thanks for the speedy fix!
