### ISSUE TITLE
Crash trying to simulate reopened West Seattle Bridge

### ISSUE THREAD

**Issue by jaredkrinke** [dabreegster/abstreet#68]
On Windows build up on 6/22, I made all the "closed" lanes on the West Seattle Bridge driving lanes (to see the impact of closing the bridge). I'm not sure if this is related to the crash, but after clicking the fourth "left arrow" button to speed up the simulation, the app went unresponsive and then disappeared.

Truncated log file is here (although the symbols in the stack trace didn't appear to load):
[output.txt](https://github.com/dabreegster/abstreet/files/4815874/output.txt)

**Comment by dabreegster** [comment]
The stack trace is pretty sparse in release mode; looks worse than usual for Windows. I've wanted to try reopening the bridge for a while; I'll repro later and figure out what broke. Today is hectic, but I promise something by Wednesday

**Comment by jaredkrinke** [comment]
Yeah, I'm sure today is interesting -- you're on the front page of Hacker News (very well deserved, by the way)! For what it's worth, there's no urgency on my side; I just hit a crash and thought I'd help by reporting it. This isn't preventing me from playing around with the game :)

Additionally, I was able to reproduce the crash on my second attempt to reopen the bridge (and, notably, making a different change didn't result in a crash). Full log attached this time:

[output.txt](https://github.com/dabreegster/abstreet/files/4816008/output.txt)

Roughly, I did the following:
* Launch
* Open Sandbox mode
* Switch to West Seattle
* Go into edit mode
* Change all the West Seattle Bridge lanes to "d" (including the bus lanes on the lower span)
* Click finish
* Click the 4th "speed arrow" button

**Comment by dabreegster** [comment]
Fixed -- there was a bug failing to recalculate stop signs when changing from construction -> driving. I also included my attempt at restoring the bridge to its former glory as a built-in proposal to play with.

Hit some UX difficulties actually making the edits, so filed #92 and #93 to not forget
