### ISSUE TITLE
Font problem or a missing language setting?

### ISSUE THREAD

**Issue by okilimu** [dabreegster/abstreet#76]
I built the simulation game from source. After starting the simulation, i see a mix of readable text and non-readable pixels, where i assume, another text should be visible.
Is there a missing font or do i have to define a prefered language for the game?
![abstreet_fontproblem](https://user-images.githubusercontent.com/192311/85369645-c155c180-b52d-11ea-9b46-38929acd973f.png)

**Comment by dabreegster** [comment]
The fonts are bundled in `data/system/fonts/`. It kind of looks like the text _is_ rendering, but very very strangely. I'll look into this soon; I think it's an issue with https://github.com/RazrFalcon/resvg. What platform are you on?

**Comment by dabreegster** [comment]
https://github.com/RazrFalcon/resvg/issues/300

**Comment by okilimu** [comment]
I use Ubuntu 16.04. LTS, local language is german.
I installed rust new today: rustup has settings.toml content
"
default_host_triple = "x86_64-unknown-linux-gnu"
default_toolchain = "stable"
profile = "default"
version = "12"
"
cargo show "cargo 1.44.1 "
Previously, older version of rust was installed. I removed it normally, then i made the new rust installation.

**Comment by dabreegster** [comment]
If you enter sandbox mode and zoom in on the center of a road, there's usually the road name in yellow. What do you see? I'm curious if this is a screen-space vs map-space scaling issue somehow

**Comment by dabreegster** [comment]
@RazrFalcon in the other bug thinks this is probably the harfbuzz library on your system. Could you:

1) install https://github.com/RazrFalcon/resvg/tree/master/usvg by doing `cargo install usvg`

2) create `foo.svg` containing `<svg width="9999" height="9999" viewBox="0 0 9999 9999" xmlns="http://www.w3.org/2000/svg"><text x="0" y="0" font-size="21" font-family="Overpass"><tspan fill="#5B5B5B">Community Proposals</tspan></text></svg>`

3) Temporarily stick the overpass font so usvg will find it: `sudo cp data/system/fonts/Overpass-Regular.ttf /usr/local/share/fonts/`

4) Run `usvg foo.svg bar.svg`

5) Send `bar.svg`. We can compare to what I get

**Comment by okilimu** [comment]
In console, i get this warning at the beginning
openstreetmap@nb15:~/software/abstreet/game$ cargo run --release
warning: unused return value of `std::vec::Vec::<T>::split_off` that must be used
   --> geom/src/polyline.rs:632:13
    |
632 |             pts.split_off(idx + 1);
    |             ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_must_use)]` on by default
    = note: use `.truncate()` if you don't need the other half

warning: 1 warning emitted

    Finished release [optimized] target(s) in 0.15s
     Running `/home/openstreetmap/software/abstreet/target/release/game`
load map...
Loading map ../data/system/maps/montlake.bin
Read ../data/system/maps/montlake.bin (4)... 0.0463s
create sim...
create sim took 0.0021s
Map and Sim cost ~11 MB
draw_map...
make DrawRoads (491)... 0.0269s
generate thick roads...

**Comment by okilimu** [comment]
here is the result in zip-archiv, directly upload of svg-file was not support in github-
the directory /usr/local/share/fonts/ was empty, is that normal?

[bar.svg.zip](https://github.com/dabreegster/abstreet/files/4821538/bar.svg.zip)

**Comment by dabreegster** [comment]
That warning is benign (but I fixed it, thanks -- your rust compiler must be a little newer than mine).

Empty /usr/local/share/fonts is normal; mine was too.

Thanks for the file! Indeed it's different than what I get. Digging in at RazrFalcon/resvg#300

**Comment by RazrFalcon** [comment]
@okilimu Hello. Can you run: `hb-shape /path/to/Overpass-Regular.ttf 'Community Proposals'`

**Comment by okilimu** [comment]
@RazrFalcon Whe i tried first, i got the information, that hb-shape is not installed.
After installation, i got as result of your request
hb-shape ./data/system/fonts/Overpass-Regular.ttf 'Community Proposals'
[C=0+663|o=1+571|m=2+866|m=3+866|u=4+577|n=5+577|i=6+260|t=7+383|y=8+543|space=9+241|P=10+645|r=11+398|o=12+571|p=13+578|o=14+571|s=15+480|a=16+539|l=17+268|s=18+480]

A new attempt to start abstreet took the same result of not-readable text (was hoping, if hb-shape would be need for abstreet ifself)

One more information: yesterday, i made the rustup installation only locally for my account and adding my path to have rust active.
Perhaps this non-systemwide istallation could be the problem?

**Comment by RazrFalcon** [comment]
Can you also run `hb-view` and send us the resulting image? Because it looks like a harfbuzz bug. But since it's an old hb version - the only way we can fix it, is to force static linking on linux. Which should be implemented on the `harfbuzz-rs` side.

**Comment by RazrFalcon** [comment]
@okilimu Looks like you can set `HARFBUZZ_SYS_NO_PKG_CONFIG=1` before building `abstreet` and it should work for now.

**Comment by okilimu** [comment]
@RazrFalcon i hope, you mean
hb-view ./data/system/fonts/Overpass-Regular.ttf 'Community Proposals' >hbview_output.txt
[hbview_output.txt](https://github.com/dabreegster/abstreet/files/4827465/hbview_output.txt)

**Comment by okilimu** [comment]
> HARFBUZZ_SYS_NO_PKG_CONFIG=1



> @okilimu Looks like you can set `HARFBUZZ_SYS_NO_PKG_CONFIG=1` before building `abstreet` and it should work for now.

i tried in bash terminal
HARFBUZZ_SYS_NO_PKG_CONFIG=1
git pull
cargo run --bin updater
cd game; RUST_BACKTRACE=1 cargo run --release

but the result is same, the text output is not readable.
I hope, i made the steps correctly

I don't want, that you take too much time for my single problem

**Comment by dabreegster** [comment]
Hi @okilimu, could you `git pull` and try again? (You'll also have to `cargo run --bin updater`, since the binary map data format has changed recently)

**Comment by okilimu** [comment]
Hello @dabreegster,
the new version works fine! Thanks for the solution.
