### ISSUE TITLE
Consider not depending on systemwide OpenSSL, at least in the binary releases

### ISSUE THREAD

**Issue by metiulekm** [dabreegster/abstreet#77]
I use LibreSSL 3.0.2 on my Linux install. When trying to run the binary release, I get in `output.txt`:

    ./game: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

However, it works fine when compiled from source, so it's merely compiled against the "wrong" library. Consider providing a feature flag that will enable the [vendored flag in `openssl`](https://docs.rs/openssl/0.10.29/openssl/#vendored), and enabling this flag when building the binary release.

**Comment by dabreegster** [comment]
Ah, that statically links OpenSSL, nice! I also see an option for a Rust-native TLS impl, which I suspect is faster to build on Github actions. I'll try that first. `reqwest` is only a dependency to pull data from https://openstreetmap.org for the parking mapping mode.
