### ISSUE TITLE
Importer crashes on Bruges

### ISSUE THREAD

**Issue by pietervdvn** [dabreegster/abstreet#84]
Input file and stacktrace are included

[Brugge-RoadsOnly.zip](https://github.com/dabreegster/abstreet/files/4820687/Brugge-RoadsOnly.zip)

```
Read Brugge-RoadsOnly.osm (14)... 1.3593s
OSM doc has 56624 nodes, 12042 ways, 9 relations
processing OSM nodes (56,624)... 0.0233s
processing OSM ways (12,042)... 0.0513s
processing OSM relations (9)... 0.0000s
0 ways of coastline
splitting up roads...
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/slice/mod.rs:2842:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:63
  14: convert_osm::split_ways::split_up_roads
  15: convert_osm::convert
  16: importer::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  21: std::panicking::try
             at src/libstd/panicking.rs:281
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: main
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.
```

**Comment by dabreegster** [comment]
I got it working, but for nicer results, a full extract, not just roads, will look much better. If you happen to know of a data source for number of trips between different areas, we could put together a more realistic scenario here.

**Comment by pietervdvn** [comment]
Great! I'm very active within OSM, so I kindof know the tradeofs. I just wanted to do a quick test for the roads to see what it would give.

**Comment by dabreegster** [comment]
Awesome! When you get a chance, please take a look at the parking mapper tool from the main screen. Do you reckon this sort of UI could be useful for specialized OSM editing? I know about the JOSM lane plugin, but I'm considering making an alternative, once there's proper web support.

**Comment by pietervdvn** [comment]
I'll definitely have a look to it! I've just managed to run `cargo run updater` (and to open a PR in the meantime).

I've also made a [StreetComplete fork](https://github.com/pietervdvn/StreetComplete/blob/master/releases/BruggeFietsstraat1.0_Width_Parallel_Sidewalk.apk) two weeks ago which asks for parking lanes, for another project...

For that project, the local cyclist lobbying group wants to know the carriage way widths in order to determine if there is enough room for cars to overtake cyclists (in the hope that we can enforce cyclestreets throughout the city center).

If you want, I'm currently also working on a [webversion of streetcomplete](https://pietervdvn.github.io/MapComplete/dist/index.html), I can make a version which asks for streetside parking too (but it is gonna take a few weeks before I'll have time for that, so no promises there).

**Comment by dabreegster** [comment]
Ah, I had looked at StreetComplete for parking a while ago, but I was intimidated by Android app dev process. A web version sounds amazing! No rush at all

**Comment by pietervdvn** [comment]
TBH, streetcomplete is quite straightforward to setup, it was only a few hours before I got it working. It boils down to installing android studio, clicking 'ok', 'I agree', 'download now', ... then opening the StreetComplete repo and pressing run, and again pressing 'OK' till it works ;p
