### ISSUE TITLE
Crash when clicking "read detailed write-up" for stay healthy street proposal

### ISSUE THREAD

**Issue by Pokechu22** [dabreegster/abstreet#97]
Under "Community Proposals", for "Convert Lake Washington Blvd to a Stay Healthy Street", selecting "Read detailed write-up" causes the game to crash.

<details>
<summary><code>output.txt</code></summary>
<pre>
Initial inner window size is PhysicalSize { width: 1366, height: 705 }, monitor is PhysicalSize { width: 1366, height: 768 }, scale factor is 1
load map...
Loading map ../data/system/maps/montlake.bin
Reading ../data/system/maps/montlake.bin: 0/4 MB... 0.0001s
Reading ../data/system/maps/montlake.bin: 0/4 MB... 0.2015s
Reading ../data/system/maps/montlake.bin: 1/4 MB... 0.4035s
Reading ../data/system/maps/montlake.bin: 2/4 MB... 0.6036s
Reading ../data/system/maps/montlake.bin: 3/4 MB... 0.8970s
Reading ../data/system/maps/montlake.bin: 4/4 MB... 1.0972s
Read ../data/system/maps/montlake.bin (4)... 1.1793s
create sim...
create sim took 0.0081s
Map and Sim cost ~0 MB
draw_map...
make DrawRoads (491)... 0.1500s
generate thick roads...
generate thick roads took 0.0158s
prepare DrawLanes: 2,347/2,381... 0.2001s
prepare DrawLanes (2,381)... 0.2029s
finalize DrawLanes (2,381)... 0.1794s
make DrawIntersections (371)... 0.1502s
generate unzoomed intersections...
generate unzoomed intersections took 0.0015s
make DrawBuildings: 2,304/3,014... 0.2001s
make DrawBuildings (3,014)... 0.2559s
upload all buildings...
upload all buildings took 0.0272s
make DrawParkingLot...
make DrawParkingLot took 0.0148s
make DrawBusStop (16)... 0.0041s
make DrawAreas (54)... 0.0002s
upload all areas...
upload all areas took 0.0001s
create quadtree...
create quadtree took 0.2849s
static DrawMap consumes 16 MB on the GPU
draw_map... plus 0.2683s
draw_map took 1.5554s
DrawMap cost ~0 MB
load map... plus 0.0406s
load map took 2.7834s
- load map took 2.7834s
  - Read ../data/system/maps/montlake.bin (4)... 1.1793s
  - create sim took 0.0081s
  - draw_map took 1.5554s
    - make DrawRoads (491)... 0.1500s
    - generate thick roads took 0.0158s
    - prepare DrawLanes (2,381)... 0.2029s
    - finalize DrawLanes (2,381)... 0.1794s
    - make DrawIntersections (371)... 0.1502s
    - generate unzoomed intersections took 0.0015s
    - make DrawBuildings (3,014)... 0.2559s
    - upload all buildings took 0.0272s
    - make DrawParkingLot took 0.0148s
    - make DrawBusStop (16)... 0.0041s
    - make DrawAreas (54)... 0.0002s
    - upload all areas took 0.0001s
    - create quadtree took 0.2849s
    - ... plus 0.2683s
  - ... plus 0.0406s
4 notes:
Loading map ../data/system/maps/montlake.bin
Map and Sim cost ~0 MB
static DrawMap consumes 16 MB on the GPU
DrawMap cost ~0 MB
1 warnings:
Parking lane Lane #2178 has no sidewalk!
- load map took 2.7834s
Unknown winit key LWin
Unknown winit key LWin
load_all_objects from ../data/system/proposals...
parse ../data/system/proposals/cap hill superblock.json...
parse ../data/system/proposals/cap hill superblock.json took 0.0008s
parse ../data/system/proposals/simplify burke corliss.json...
parse ../data/system/proposals/simplify burke corliss.json took 0.0003s
parse ../data/system/proposals/stay healthy lake wash blvd.json...
parse ../data/system/proposals/stay healthy lake wash blvd.json took 0.0005s
load_all_objects from ../data/system/proposals... plus 0.0008s
load_all_objects from ../data/system/proposals took 0.0023s
- load_all_objects from ../data/system/proposals took 0.0023s
  - parse ../data/system/proposals/cap hill superblock.json took 0.0008s
  - parse ../data/system/proposals/simplify burke corliss.json took 0.0003s
  - parse ../data/system/proposals/stay healthy lake wash blvd.json took 0.0005s
  - ... plus 0.0008s
- load_all_objects from ../data/system/proposals took 0.0023s
load_all_objects from ../data/system/proposals...
parse ../data/system/proposals/cap hill superblock.json...
parse ../data/system/proposals/cap hill superblock.json took 0.0007s
parse ../data/system/proposals/simplify burke corliss.json...
parse ../data/system/proposals/simplify burke corliss.json took 0.0003s
parse ../data/system/proposals/stay healthy lake wash blvd.json...
parse ../data/system/proposals/stay healthy lake wash blvd.json took 0.0005s
load_all_objects from ../data/system/proposals... plus 0.0006s
load_all_objects from ../data/system/proposals took 0.0021s
- load_all_objects from ../data/system/proposals took 0.0021s
  - parse ../data/system/proposals/cap hill superblock.json took 0.0007s
  - parse ../data/system/proposals/simplify burke corliss.json took 0.0003s
  - parse ../data/system/proposals/stay healthy lake wash blvd.json took 0.0005s
  - ... plus 0.0006s
- load_all_objects from ../data/system/proposals took 0.0021s
Unknown winit key LWin
Unknown winit key LWin
Unknown winit key LWin
Unknown winit key LWin
load_all_objects from ../data/system/proposals...
parse ../data/system/proposals/cap hill superblock.json...
parse ../data/system/proposals/cap hill superblock.json took 0.0006s
parse ../data/system/proposals/simplify burke corliss.json...
parse ../data/system/proposals/simplify burke corliss.json took 0.0002s
parse ../data/system/proposals/stay healthy lake wash blvd.json...
parse ../data/system/proposals/stay healthy lake wash blvd.json took 0.0004s
load_all_objects from ../data/system/proposals... plus 0.0006s
load_all_objects from ../data/system/proposals took 0.0019s
- load_all_objects from ../data/system/proposals took 0.0019s
  - parse ../data/system/proposals/cap hill superblock.json took 0.0006s
  - parse ../data/system/proposals/simplify burke corliss.json took 0.0002s
  - parse ../data/system/proposals/stay healthy lake wash blvd.json took 0.0004s
  - ... plus 0.0006s
- load_all_objects from ../data/system/proposals took 0.0019s
Unknown winit key LWin
Unknown winit key LWin
Unknown winit key LWin
Unknown winit key LWin
load_all_objects from ../data/system/proposals...
parse ../data/system/proposals/cap hill superblock.json...
parse ../data/system/proposals/cap hill superblock.json took 0.0006s
parse ../data/system/proposals/simplify burke corliss.json...
parse ../data/system/proposals/simplify burke corliss.json took 0.0002s
parse ../data/system/proposals/stay healthy lake wash blvd.json...
parse ../data/system/proposals/stay healthy lake wash blvd.json took 0.0004s
load_all_objects from ../data/system/proposals... plus 0.0006s
load_all_objects from ../data/system/proposals took 0.0018s
- load_all_objects from ../data/system/proposals took 0.0018s
  - parse ../data/system/proposals/cap hill superblock.json took 0.0006s
  - parse ../data/system/proposals/simplify burke corliss.json took 0.0002s
  - parse ../data/system/proposals/stay healthy lake wash blvd.json took 0.0004s
  - ... plus 0.0006s
- load_all_objects from ../data/system/proposals took 0.0018s
Unknown winit key LWin
Unknown winit key LWin
thread 'main' panicked at 'either event handler is re-entrant (likely), or no event handler is registered (very unlikely)', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:235:37
stack backtrace:
   0: &lt;unknown&gt;
   1: &lt;unknown&gt;
   2: &lt;unknown&gt;
   3: &lt;unknown&gt;
   4: &lt;unknown&gt;
   5: &lt;unknown&gt;
   6: &lt;unknown&gt;
   7: &lt;unknown&gt;
   8: &lt;unknown&gt;
   9: &lt;unknown&gt;
  10: &lt;unknown&gt;
  11: &lt;unknown&gt;
  12: &lt;unknown&gt;
  13: &lt;unknown&gt;
  14: &lt;unknown&gt;
  15: &lt;unknown&gt;
  16: &lt;unknown&gt;
  17: &lt;unknown&gt;
  18: &lt;unknown&gt;
  19: DefSubclassProc
  20: DefSubclassProc
  21: CallWindowProcW
  22: DispatchMessageW
  23: SendMessageTimeoutW
  24: KiUserCallbackDispatcher
  25: NtUserDispatchMessage
  26: DispatchMessageW
  27: SHSetTemporaryPropertyForItem
  28: Ordinal900
  29: Ordinal99
  30: ShellExecuteExW
  31: ShellExecuteExW
  32: ShellExecuteW
  33: &lt;unknown&gt;
  34: &lt;unknown&gt;
  35: &lt;unknown&gt;
  36: &lt;unknown&gt;
  37: &lt;unknown&gt;
  38: &lt;unknown&gt;
  39: &lt;unknown&gt;
  40: &lt;unknown&gt;
  41: &lt;unknown&gt;
  42: &lt;unknown&gt;
  43: &lt;unknown&gt;
  44: &lt;unknown&gt;
  45: &lt;unknown&gt;
  46: &lt;unknown&gt;
  47: &lt;unknown&gt;
  48: &lt;unknown&gt;
  49: &lt;unknown&gt;
  50: &lt;unknown&gt;
  51: &lt;unknown&gt;
  52: DefSubclassProc
  53: DefSubclassProc
  54: CallWindowProcW
  55: CallWindowProcW
  56: glPushClientAttrib
  57: CallWindowProcW
  58: DispatchMessageW
  59: &lt;unknown&gt;
  60: &lt;unknown&gt;
  61: &lt;unknown&gt;
  62: &lt;unknown&gt;
  63: &lt;unknown&gt;
  64: &lt;unknown&gt;
  65: &lt;unknown&gt;
  66: &lt;unknown&gt;
  67: &lt;unknown&gt;
  68: &lt;unknown&gt;
  69: BaseThreadInitThunk
  70: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</pre>
</details>

The proposal page (https://dabreegster.github.io/abstreet/lake_wash/proposal.html) does open correctly in my default browser (Firefox), though.

**Comment by dabreegster** [comment]
I'm using https://crates.io/crates/webbrowser to open URLs. Huh, maybe it interacts strangely with winit (the window management library) strangely on Windows. Looking into it

**Comment by dabreegster** [comment]
I think this is the same root cause as https://github.com/rust-windowing/winit/issues/1602 and https://github.com/rust-windowing/winit/issues/1587.

**Comment by dabreegster** [comment]
Waiting for https://github.com/rust-windowing/winit/commit/dd866a74a690d37fdd11385741dee06e9f7cd02f to make it into a winit release

**Comment by dabreegster** [comment]
We're now pinning to a new winit build that should have the fix. Give https://github.com/dabreegster/abstreet/releases/tag/v0.2.8 a shot and please reopen the bug if it's still happening. Thanks!

**Comment by Pokechu22** [comment]
The stay healthy street proposal doesn't seem to exist in that version (I don't see any proposals at all), but "See full credits" under About also opens a web page; that one also crashed in v0.2.0d, but now doesn't crash in v0.2.8.  So, yep, it's fixed, thanks!

**Comment by dabreegster** [comment]
Great! Indeed the proposals are missing from the release; I'll look into that
