### ISSUE TITLE
thread 'main' panicked at 'PL with total length 6.2334m and 4 pts has ~dupe adjacent pts ...

### ISSUE THREAD

**Issue by jraymakers** [dabreegster/abstreet#98]
I was running with RUST_BACKTRACE=1 this time so the output has more info, including point coords; see attached.

[abstreet_output2.txt](https://github.com/dabreegster/abstreet/files/4823747/abstreet_output2.txt)
[downtown.json.txt](https://github.com/dabreegster/abstreet/files/4823750/downtown.json.txt)

**Comment by dabreegster** [comment]
Started [an attempt](https://github.com/dabreegster/abstreet/commit/5208cec256ea31e32c92b5103e2e8de464348ccb) to fix this at a lower layer, but it breaks some map importing. I need to figure out a more robust way of handling tiny geometry.

**Comment by dabreegster** [comment]
I overhauled lots of the base geometry code. Lots of crashes should either be avoided now or have much more useful debug info. Closing this bug for now; please send the new log when you encounter it again.
